# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  LIL_ENDIAN = 1234
  BIG_ENDIAN = 4321

  # Enum


  # Typedef


  # Struct


  # Function

  def self.setup_endian_symbols(output_error = false)
    symbols = [
      :SDL_SwapFloat,
    ]
    apis = {
      :SDL_SwapFloat => :SwapFloat,
    }
    args = {
      :SDL_SwapFloat => [:float],
    }
    retvals = {
      :SDL_SwapFloat => :float,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

