# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  STANDARD_GRAVITY = 9.80665

  # Enum

  SENSOR_INVALID = -1
  SENSOR_UNKNOWN = 0
  SENSOR_ACCEL = 1
  SENSOR_GYRO = 2
  SENSOR_ACCEL_L = 3
  SENSOR_GYRO_L = 4
  SENSOR_ACCEL_R = 5
  SENSOR_GYRO_R = 6

  # Typedef

  typedef :uint, :SDL_SensorID
  typedef :int, :SDL_SensorType

  # Struct


  # Function

  def self.setup_sensor_symbols(output_error = false)
    symbols = [
      :SDL_GetSensors,
      :SDL_GetSensorNameForID,
      :SDL_GetSensorTypeForID,
      :SDL_GetSensorNonPortableTypeForID,
      :SDL_OpenSensor,
      :SDL_GetSensorFromID,
      :SDL_GetSensorProperties,
      :SDL_GetSensorName,
      :SDL_GetSensorType,
      :SDL_GetSensorNonPortableType,
      :SDL_GetSensorID,
      :SDL_GetSensorData,
      :SDL_CloseSensor,
      :SDL_UpdateSensors,
    ]
    apis = {
      :SDL_GetSensors => :GetSensors,
      :SDL_GetSensorNameForID => :GetSensorNameForID,
      :SDL_GetSensorTypeForID => :GetSensorTypeForID,
      :SDL_GetSensorNonPortableTypeForID => :GetSensorNonPortableTypeForID,
      :SDL_OpenSensor => :OpenSensor,
      :SDL_GetSensorFromID => :GetSensorFromID,
      :SDL_GetSensorProperties => :GetSensorProperties,
      :SDL_GetSensorName => :GetSensorName,
      :SDL_GetSensorType => :GetSensorType,
      :SDL_GetSensorNonPortableType => :GetSensorNonPortableType,
      :SDL_GetSensorID => :GetSensorID,
      :SDL_GetSensorData => :GetSensorData,
      :SDL_CloseSensor => :CloseSensor,
      :SDL_UpdateSensors => :UpdateSensors,
    }
    args = {
      :SDL_GetSensors => [:pointer],
      :SDL_GetSensorNameForID => [:uint],
      :SDL_GetSensorTypeForID => [:uint],
      :SDL_GetSensorNonPortableTypeForID => [:uint],
      :SDL_OpenSensor => [:uint],
      :SDL_GetSensorFromID => [:uint],
      :SDL_GetSensorProperties => [:pointer],
      :SDL_GetSensorName => [:pointer],
      :SDL_GetSensorType => [:pointer],
      :SDL_GetSensorNonPortableType => [:pointer],
      :SDL_GetSensorID => [:pointer],
      :SDL_GetSensorData => [:pointer, :pointer, :int],
      :SDL_CloseSensor => [:pointer],
      :SDL_UpdateSensors => [],
    }
    retvals = {
      :SDL_GetSensors => :pointer,
      :SDL_GetSensorNameForID => :pointer,
      :SDL_GetSensorTypeForID => :int,
      :SDL_GetSensorNonPortableTypeForID => :int,
      :SDL_OpenSensor => :pointer,
      :SDL_GetSensorFromID => :pointer,
      :SDL_GetSensorProperties => :uint,
      :SDL_GetSensorName => :pointer,
      :SDL_GetSensorType => :int,
      :SDL_GetSensorNonPortableType => :int,
      :SDL_GetSensorID => :uint,
      :SDL_GetSensorData => :bool,
      :SDL_CloseSensor => :void,
      :SDL_UpdateSensors => :void,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

