# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'
require_relative 'sdl3_joystick'

module SDL
  extend FFI::Library
  # Define/Macro


  # Enum

  GAMEPAD_TYPE_UNKNOWN = 0
  GAMEPAD_TYPE_STANDARD = 1
  GAMEPAD_TYPE_XBOX360 = 2
  GAMEPAD_TYPE_XBOXONE = 3
  GAMEPAD_TYPE_PS3 = 4
  GAMEPAD_TYPE_PS4 = 5
  GAMEPAD_TYPE_PS5 = 6
  GAMEPAD_TYPE_NINTENDO_SWITCH_PRO = 7
  GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT = 8
  GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT = 9
  GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR = 10
  GAMEPAD_TYPE_COUNT = 11
  GAMEPAD_BUTTON_INVALID = -1
  GAMEPAD_BUTTON_SOUTH = 0
  GAMEPAD_BUTTON_EAST = 1
  GAMEPAD_BUTTON_WEST = 2
  GAMEPAD_BUTTON_NORTH = 3
  GAMEPAD_BUTTON_BACK = 4
  GAMEPAD_BUTTON_GUIDE = 5
  GAMEPAD_BUTTON_START = 6
  GAMEPAD_BUTTON_LEFT_STICK = 7
  GAMEPAD_BUTTON_RIGHT_STICK = 8
  GAMEPAD_BUTTON_LEFT_SHOULDER = 9
  GAMEPAD_BUTTON_RIGHT_SHOULDER = 10
  GAMEPAD_BUTTON_DPAD_UP = 11
  GAMEPAD_BUTTON_DPAD_DOWN = 12
  GAMEPAD_BUTTON_DPAD_LEFT = 13
  GAMEPAD_BUTTON_DPAD_RIGHT = 14
  GAMEPAD_BUTTON_MISC1 = 15
  GAMEPAD_BUTTON_RIGHT_PADDLE1 = 16
  GAMEPAD_BUTTON_LEFT_PADDLE1 = 17
  GAMEPAD_BUTTON_RIGHT_PADDLE2 = 18
  GAMEPAD_BUTTON_LEFT_PADDLE2 = 19
  GAMEPAD_BUTTON_TOUCHPAD = 20
  GAMEPAD_BUTTON_MISC2 = 21
  GAMEPAD_BUTTON_MISC3 = 22
  GAMEPAD_BUTTON_MISC4 = 23
  GAMEPAD_BUTTON_MISC5 = 24
  GAMEPAD_BUTTON_MISC6 = 25
  GAMEPAD_BUTTON_COUNT = 26
  GAMEPAD_BUTTON_LABEL_UNKNOWN = 0
  GAMEPAD_BUTTON_LABEL_A = 1
  GAMEPAD_BUTTON_LABEL_B = 2
  GAMEPAD_BUTTON_LABEL_X = 3
  GAMEPAD_BUTTON_LABEL_Y = 4
  GAMEPAD_BUTTON_LABEL_CROSS = 5
  GAMEPAD_BUTTON_LABEL_CIRCLE = 6
  GAMEPAD_BUTTON_LABEL_SQUARE = 7
  GAMEPAD_BUTTON_LABEL_TRIANGLE = 8
  GAMEPAD_AXIS_INVALID = -1
  GAMEPAD_AXIS_LEFTX = 0
  GAMEPAD_AXIS_LEFTY = 1
  GAMEPAD_AXIS_RIGHTX = 2
  GAMEPAD_AXIS_RIGHTY = 3
  GAMEPAD_AXIS_LEFT_TRIGGER = 4
  GAMEPAD_AXIS_RIGHT_TRIGGER = 5
  GAMEPAD_AXIS_COUNT = 6
  GAMEPAD_BINDTYPE_NONE = 0
  GAMEPAD_BINDTYPE_BUTTON = 1
  GAMEPAD_BINDTYPE_AXIS = 2
  GAMEPAD_BINDTYPE_HAT = 3

  # Typedef


  class GamepadBinding_value_axis < FFI::Struct
    layout(
        :axis, :int,
        :axis_min, :int,
        :axis_max, :int,
    )
  end

  class GamepadBinding_value_hat < FFI::Struct
    layout(
        :hat, :int,
        :hat_mask, :int,
    )
  end

  class GamepadBinding_input < FFI::Struct
    layout(
        :button, :int,
        :axis, GamepadBinding_value_axis,
        :hat, GamepadBinding_value_hat,
    )
  end

  class GamepadBinding_output < FFI::Struct
    layout(
        :button, :int,
        :axis, GamepadBinding_value_axis,
    )
  end

  class GamepadBinding < FFI::Struct
    layout(
        :input_type, :int,
        :input, GamepadBinding_input,
        :output_type, :int,
        :output, GamepadBinding_output,
    )
  end

  typedef :int, :SDL_GamepadType
  typedef :int, :SDL_GamepadButton
  typedef :int, :SDL_GamepadButtonLabel
  typedef :int, :SDL_GamepadAxis
  typedef :int, :SDL_GamepadBindingType

  # Struct


  # Function

  def self.setup_gamepad_symbols(output_error = false)
    symbols = [
      :SDL_AddGamepadMapping,
      :SDL_AddGamepadMappingsFromIO,
      :SDL_AddGamepadMappingsFromFile,
      :SDL_ReloadGamepadMappings,
      :SDL_GetGamepadMappings,
      :SDL_GetGamepadMappingForGUID,
      :SDL_GetGamepadMapping,
      :SDL_SetGamepadMapping,
      :SDL_HasGamepad,
      :SDL_GetGamepads,
      :SDL_IsGamepad,
      :SDL_GetGamepadNameForID,
      :SDL_GetGamepadPathForID,
      :SDL_GetGamepadPlayerIndexForID,
      :SDL_GetGamepadGUIDForID,
      :SDL_GetGamepadVendorForID,
      :SDL_GetGamepadProductForID,
      :SDL_GetGamepadProductVersionForID,
      :SDL_GetGamepadTypeForID,
      :SDL_GetRealGamepadTypeForID,
      :SDL_GetGamepadMappingForID,
      :SDL_OpenGamepad,
      :SDL_GetGamepadFromID,
      :SDL_GetGamepadFromPlayerIndex,
      :SDL_GetGamepadProperties,
      :SDL_GetGamepadID,
      :SDL_GetGamepadName,
      :SDL_GetGamepadPath,
      :SDL_GetGamepadType,
      :SDL_GetRealGamepadType,
      :SDL_GetGamepadPlayerIndex,
      :SDL_SetGamepadPlayerIndex,
      :SDL_GetGamepadVendor,
      :SDL_GetGamepadProduct,
      :SDL_GetGamepadProductVersion,
      :SDL_GetGamepadFirmwareVersion,
      :SDL_GetGamepadSerial,
      :SDL_GetGamepadSteamHandle,
      :SDL_GetGamepadConnectionState,
      :SDL_GetGamepadPowerInfo,
      :SDL_GamepadConnected,
      :SDL_GetGamepadJoystick,
      :SDL_SetGamepadEventsEnabled,
      :SDL_GamepadEventsEnabled,
      :SDL_GetGamepadBindings,
      :SDL_UpdateGamepads,
      :SDL_GetGamepadTypeFromString,
      :SDL_GetGamepadStringForType,
      :SDL_GetGamepadAxisFromString,
      :SDL_GetGamepadStringForAxis,
      :SDL_GamepadHasAxis,
      :SDL_GetGamepadAxis,
      :SDL_GetGamepadButtonFromString,
      :SDL_GetGamepadStringForButton,
      :SDL_GamepadHasButton,
      :SDL_GetGamepadButton,
      :SDL_GetGamepadButtonLabelForType,
      :SDL_GetGamepadButtonLabel,
      :SDL_GetNumGamepadTouchpads,
      :SDL_GetNumGamepadTouchpadFingers,
      :SDL_GetGamepadTouchpadFinger,
      :SDL_GamepadHasSensor,
      :SDL_SetGamepadSensorEnabled,
      :SDL_GamepadSensorEnabled,
      :SDL_GetGamepadSensorDataRate,
      :SDL_GetGamepadSensorData,
      :SDL_RumbleGamepad,
      :SDL_RumbleGamepadTriggers,
      :SDL_SetGamepadLED,
      :SDL_SendGamepadEffect,
      :SDL_CloseGamepad,
      :SDL_GetGamepadAppleSFSymbolsNameForButton,
      :SDL_GetGamepadAppleSFSymbolsNameForAxis,
    ]
    apis = {
      :SDL_AddGamepadMapping => :AddGamepadMapping,
      :SDL_AddGamepadMappingsFromIO => :AddGamepadMappingsFromIO,
      :SDL_AddGamepadMappingsFromFile => :AddGamepadMappingsFromFile,
      :SDL_ReloadGamepadMappings => :ReloadGamepadMappings,
      :SDL_GetGamepadMappings => :GetGamepadMappings,
      :SDL_GetGamepadMappingForGUID => :GetGamepadMappingForGUID,
      :SDL_GetGamepadMapping => :GetGamepadMapping,
      :SDL_SetGamepadMapping => :SetGamepadMapping,
      :SDL_HasGamepad => :HasGamepad,
      :SDL_GetGamepads => :GetGamepads,
      :SDL_IsGamepad => :IsGamepad,
      :SDL_GetGamepadNameForID => :GetGamepadNameForID,
      :SDL_GetGamepadPathForID => :GetGamepadPathForID,
      :SDL_GetGamepadPlayerIndexForID => :GetGamepadPlayerIndexForID,
      :SDL_GetGamepadGUIDForID => :GetGamepadGUIDForID,
      :SDL_GetGamepadVendorForID => :GetGamepadVendorForID,
      :SDL_GetGamepadProductForID => :GetGamepadProductForID,
      :SDL_GetGamepadProductVersionForID => :GetGamepadProductVersionForID,
      :SDL_GetGamepadTypeForID => :GetGamepadTypeForID,
      :SDL_GetRealGamepadTypeForID => :GetRealGamepadTypeForID,
      :SDL_GetGamepadMappingForID => :GetGamepadMappingForID,
      :SDL_OpenGamepad => :OpenGamepad,
      :SDL_GetGamepadFromID => :GetGamepadFromID,
      :SDL_GetGamepadFromPlayerIndex => :GetGamepadFromPlayerIndex,
      :SDL_GetGamepadProperties => :GetGamepadProperties,
      :SDL_GetGamepadID => :GetGamepadID,
      :SDL_GetGamepadName => :GetGamepadName,
      :SDL_GetGamepadPath => :GetGamepadPath,
      :SDL_GetGamepadType => :GetGamepadType,
      :SDL_GetRealGamepadType => :GetRealGamepadType,
      :SDL_GetGamepadPlayerIndex => :GetGamepadPlayerIndex,
      :SDL_SetGamepadPlayerIndex => :SetGamepadPlayerIndex,
      :SDL_GetGamepadVendor => :GetGamepadVendor,
      :SDL_GetGamepadProduct => :GetGamepadProduct,
      :SDL_GetGamepadProductVersion => :GetGamepadProductVersion,
      :SDL_GetGamepadFirmwareVersion => :GetGamepadFirmwareVersion,
      :SDL_GetGamepadSerial => :GetGamepadSerial,
      :SDL_GetGamepadSteamHandle => :GetGamepadSteamHandle,
      :SDL_GetGamepadConnectionState => :GetGamepadConnectionState,
      :SDL_GetGamepadPowerInfo => :GetGamepadPowerInfo,
      :SDL_GamepadConnected => :GamepadConnected,
      :SDL_GetGamepadJoystick => :GetGamepadJoystick,
      :SDL_SetGamepadEventsEnabled => :SetGamepadEventsEnabled,
      :SDL_GamepadEventsEnabled => :GamepadEventsEnabled,
      :SDL_GetGamepadBindings => :GetGamepadBindings,
      :SDL_UpdateGamepads => :UpdateGamepads,
      :SDL_GetGamepadTypeFromString => :GetGamepadTypeFromString,
      :SDL_GetGamepadStringForType => :GetGamepadStringForType,
      :SDL_GetGamepadAxisFromString => :GetGamepadAxisFromString,
      :SDL_GetGamepadStringForAxis => :GetGamepadStringForAxis,
      :SDL_GamepadHasAxis => :GamepadHasAxis,
      :SDL_GetGamepadAxis => :GetGamepadAxis,
      :SDL_GetGamepadButtonFromString => :GetGamepadButtonFromString,
      :SDL_GetGamepadStringForButton => :GetGamepadStringForButton,
      :SDL_GamepadHasButton => :GamepadHasButton,
      :SDL_GetGamepadButton => :GetGamepadButton,
      :SDL_GetGamepadButtonLabelForType => :GetGamepadButtonLabelForType,
      :SDL_GetGamepadButtonLabel => :GetGamepadButtonLabel,
      :SDL_GetNumGamepadTouchpads => :GetNumGamepadTouchpads,
      :SDL_GetNumGamepadTouchpadFingers => :GetNumGamepadTouchpadFingers,
      :SDL_GetGamepadTouchpadFinger => :GetGamepadTouchpadFinger,
      :SDL_GamepadHasSensor => :GamepadHasSensor,
      :SDL_SetGamepadSensorEnabled => :SetGamepadSensorEnabled,
      :SDL_GamepadSensorEnabled => :GamepadSensorEnabled,
      :SDL_GetGamepadSensorDataRate => :GetGamepadSensorDataRate,
      :SDL_GetGamepadSensorData => :GetGamepadSensorData,
      :SDL_RumbleGamepad => :RumbleGamepad,
      :SDL_RumbleGamepadTriggers => :RumbleGamepadTriggers,
      :SDL_SetGamepadLED => :SetGamepadLED,
      :SDL_SendGamepadEffect => :SendGamepadEffect,
      :SDL_CloseGamepad => :CloseGamepad,
      :SDL_GetGamepadAppleSFSymbolsNameForButton => :GetGamepadAppleSFSymbolsNameForButton,
      :SDL_GetGamepadAppleSFSymbolsNameForAxis => :GetGamepadAppleSFSymbolsNameForAxis,
    }
    args = {
      :SDL_AddGamepadMapping => [:pointer],
      :SDL_AddGamepadMappingsFromIO => [:pointer, :bool],
      :SDL_AddGamepadMappingsFromFile => [:pointer],
      :SDL_ReloadGamepadMappings => [],
      :SDL_GetGamepadMappings => [:pointer],
      :SDL_GetGamepadMappingForGUID => [GUID.by_value],
      :SDL_GetGamepadMapping => [:pointer],
      :SDL_SetGamepadMapping => [:uint, :pointer],
      :SDL_HasGamepad => [],
      :SDL_GetGamepads => [:pointer],
      :SDL_IsGamepad => [:uint],
      :SDL_GetGamepadNameForID => [:uint],
      :SDL_GetGamepadPathForID => [:uint],
      :SDL_GetGamepadPlayerIndexForID => [:uint],
      :SDL_GetGamepadGUIDForID => [:uint],
      :SDL_GetGamepadVendorForID => [:uint],
      :SDL_GetGamepadProductForID => [:uint],
      :SDL_GetGamepadProductVersionForID => [:uint],
      :SDL_GetGamepadTypeForID => [:uint],
      :SDL_GetRealGamepadTypeForID => [:uint],
      :SDL_GetGamepadMappingForID => [:uint],
      :SDL_OpenGamepad => [:uint],
      :SDL_GetGamepadFromID => [:uint],
      :SDL_GetGamepadFromPlayerIndex => [:int],
      :SDL_GetGamepadProperties => [:pointer],
      :SDL_GetGamepadID => [:pointer],
      :SDL_GetGamepadName => [:pointer],
      :SDL_GetGamepadPath => [:pointer],
      :SDL_GetGamepadType => [:pointer],
      :SDL_GetRealGamepadType => [:pointer],
      :SDL_GetGamepadPlayerIndex => [:pointer],
      :SDL_SetGamepadPlayerIndex => [:pointer, :int],
      :SDL_GetGamepadVendor => [:pointer],
      :SDL_GetGamepadProduct => [:pointer],
      :SDL_GetGamepadProductVersion => [:pointer],
      :SDL_GetGamepadFirmwareVersion => [:pointer],
      :SDL_GetGamepadSerial => [:pointer],
      :SDL_GetGamepadSteamHandle => [:pointer],
      :SDL_GetGamepadConnectionState => [:pointer],
      :SDL_GetGamepadPowerInfo => [:pointer, :pointer],
      :SDL_GamepadConnected => [:pointer],
      :SDL_GetGamepadJoystick => [:pointer],
      :SDL_SetGamepadEventsEnabled => [:bool],
      :SDL_GamepadEventsEnabled => [],
      :SDL_GetGamepadBindings => [:pointer, :pointer],
      :SDL_UpdateGamepads => [],
      :SDL_GetGamepadTypeFromString => [:pointer],
      :SDL_GetGamepadStringForType => [:int],
      :SDL_GetGamepadAxisFromString => [:pointer],
      :SDL_GetGamepadStringForAxis => [:int],
      :SDL_GamepadHasAxis => [:pointer, :int],
      :SDL_GetGamepadAxis => [:pointer, :int],
      :SDL_GetGamepadButtonFromString => [:pointer],
      :SDL_GetGamepadStringForButton => [:int],
      :SDL_GamepadHasButton => [:pointer, :int],
      :SDL_GetGamepadButton => [:pointer, :int],
      :SDL_GetGamepadButtonLabelForType => [:int, :int],
      :SDL_GetGamepadButtonLabel => [:pointer, :int],
      :SDL_GetNumGamepadTouchpads => [:pointer],
      :SDL_GetNumGamepadTouchpadFingers => [:pointer, :int],
      :SDL_GetGamepadTouchpadFinger => [:pointer, :int, :int, :pointer, :pointer, :pointer, :pointer],
      :SDL_GamepadHasSensor => [:pointer, :int],
      :SDL_SetGamepadSensorEnabled => [:pointer, :int, :bool],
      :SDL_GamepadSensorEnabled => [:pointer, :int],
      :SDL_GetGamepadSensorDataRate => [:pointer, :int],
      :SDL_GetGamepadSensorData => [:pointer, :int, :pointer, :int],
      :SDL_RumbleGamepad => [:pointer, :ushort, :ushort, :uint],
      :SDL_RumbleGamepadTriggers => [:pointer, :ushort, :ushort, :uint],
      :SDL_SetGamepadLED => [:pointer, :uchar, :uchar, :uchar],
      :SDL_SendGamepadEffect => [:pointer, :pointer, :int],
      :SDL_CloseGamepad => [:pointer],
      :SDL_GetGamepadAppleSFSymbolsNameForButton => [:pointer, :int],
      :SDL_GetGamepadAppleSFSymbolsNameForAxis => [:pointer, :int],
    }
    retvals = {
      :SDL_AddGamepadMapping => :int,
      :SDL_AddGamepadMappingsFromIO => :int,
      :SDL_AddGamepadMappingsFromFile => :int,
      :SDL_ReloadGamepadMappings => :bool,
      :SDL_GetGamepadMappings => :pointer,
      :SDL_GetGamepadMappingForGUID => :pointer,
      :SDL_GetGamepadMapping => :pointer,
      :SDL_SetGamepadMapping => :bool,
      :SDL_HasGamepad => :bool,
      :SDL_GetGamepads => :pointer,
      :SDL_IsGamepad => :bool,
      :SDL_GetGamepadNameForID => :pointer,
      :SDL_GetGamepadPathForID => :pointer,
      :SDL_GetGamepadPlayerIndexForID => :int,
      :SDL_GetGamepadGUIDForID => GUID.by_value,
      :SDL_GetGamepadVendorForID => :ushort,
      :SDL_GetGamepadProductForID => :ushort,
      :SDL_GetGamepadProductVersionForID => :ushort,
      :SDL_GetGamepadTypeForID => :int,
      :SDL_GetRealGamepadTypeForID => :int,
      :SDL_GetGamepadMappingForID => :pointer,
      :SDL_OpenGamepad => :pointer,
      :SDL_GetGamepadFromID => :pointer,
      :SDL_GetGamepadFromPlayerIndex => :pointer,
      :SDL_GetGamepadProperties => :uint,
      :SDL_GetGamepadID => :uint,
      :SDL_GetGamepadName => :pointer,
      :SDL_GetGamepadPath => :pointer,
      :SDL_GetGamepadType => :int,
      :SDL_GetRealGamepadType => :int,
      :SDL_GetGamepadPlayerIndex => :int,
      :SDL_SetGamepadPlayerIndex => :bool,
      :SDL_GetGamepadVendor => :ushort,
      :SDL_GetGamepadProduct => :ushort,
      :SDL_GetGamepadProductVersion => :ushort,
      :SDL_GetGamepadFirmwareVersion => :ushort,
      :SDL_GetGamepadSerial => :pointer,
      :SDL_GetGamepadSteamHandle => :ulong_long,
      :SDL_GetGamepadConnectionState => :int,
      :SDL_GetGamepadPowerInfo => :int,
      :SDL_GamepadConnected => :bool,
      :SDL_GetGamepadJoystick => :pointer,
      :SDL_SetGamepadEventsEnabled => :void,
      :SDL_GamepadEventsEnabled => :bool,
      :SDL_GetGamepadBindings => :pointer,
      :SDL_UpdateGamepads => :void,
      :SDL_GetGamepadTypeFromString => :int,
      :SDL_GetGamepadStringForType => :pointer,
      :SDL_GetGamepadAxisFromString => :int,
      :SDL_GetGamepadStringForAxis => :pointer,
      :SDL_GamepadHasAxis => :bool,
      :SDL_GetGamepadAxis => :short,
      :SDL_GetGamepadButtonFromString => :int,
      :SDL_GetGamepadStringForButton => :pointer,
      :SDL_GamepadHasButton => :bool,
      :SDL_GetGamepadButton => :bool,
      :SDL_GetGamepadButtonLabelForType => :int,
      :SDL_GetGamepadButtonLabel => :int,
      :SDL_GetNumGamepadTouchpads => :int,
      :SDL_GetNumGamepadTouchpadFingers => :int,
      :SDL_GetGamepadTouchpadFinger => :bool,
      :SDL_GamepadHasSensor => :bool,
      :SDL_SetGamepadSensorEnabled => :bool,
      :SDL_GamepadSensorEnabled => :bool,
      :SDL_GetGamepadSensorDataRate => :float,
      :SDL_GetGamepadSensorData => :bool,
      :SDL_RumbleGamepad => :bool,
      :SDL_RumbleGamepadTriggers => :bool,
      :SDL_SetGamepadLED => :bool,
      :SDL_SendGamepadEffect => :bool,
      :SDL_CloseGamepad => :void,
      :SDL_GetGamepadAppleSFSymbolsNameForButton => :pointer,
      :SDL_GetGamepadAppleSFSymbolsNameForAxis => :pointer,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

