# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro


  # Enum


  # Typedef

  callback :SDL_ClipboardDataCallback, [:pointer, :pointer, :pointer], :pointer
  callback :SDL_ClipboardCleanupCallback, [:pointer], :void

  # Struct


  # Function

  def self.setup_clipboard_symbols(output_error = false)
    symbols = [
      :SDL_SetClipboardText,
      :SDL_GetClipboardText,
      :SDL_HasClipboardText,
      :SDL_SetPrimarySelectionText,
      :SDL_GetPrimarySelectionText,
      :SDL_HasPrimarySelectionText,
      :SDL_SetClipboardData,
      :SDL_ClearClipboardData,
      :SDL_GetClipboardData,
      :SDL_HasClipboardData,
      :SDL_GetClipboardMimeTypes,
    ]
    apis = {
      :SDL_SetClipboardText => :SetClipboardText,
      :SDL_GetClipboardText => :GetClipboardText,
      :SDL_HasClipboardText => :HasClipboardText,
      :SDL_SetPrimarySelectionText => :SetPrimarySelectionText,
      :SDL_GetPrimarySelectionText => :GetPrimarySelectionText,
      :SDL_HasPrimarySelectionText => :HasPrimarySelectionText,
      :SDL_SetClipboardData => :SetClipboardData,
      :SDL_ClearClipboardData => :ClearClipboardData,
      :SDL_GetClipboardData => :GetClipboardData,
      :SDL_HasClipboardData => :HasClipboardData,
      :SDL_GetClipboardMimeTypes => :GetClipboardMimeTypes,
    }
    args = {
      :SDL_SetClipboardText => [:pointer],
      :SDL_GetClipboardText => [],
      :SDL_HasClipboardText => [],
      :SDL_SetPrimarySelectionText => [:pointer],
      :SDL_GetPrimarySelectionText => [],
      :SDL_HasPrimarySelectionText => [],
      :SDL_SetClipboardData => [:SDL_ClipboardDataCallback, :SDL_ClipboardCleanupCallback, :pointer, :pointer, :ulong_long],
      :SDL_ClearClipboardData => [],
      :SDL_GetClipboardData => [:pointer, :pointer],
      :SDL_HasClipboardData => [:pointer],
      :SDL_GetClipboardMimeTypes => [:pointer],
    }
    retvals = {
      :SDL_SetClipboardText => :bool,
      :SDL_GetClipboardText => :pointer,
      :SDL_HasClipboardText => :bool,
      :SDL_SetPrimarySelectionText => :bool,
      :SDL_GetPrimarySelectionText => :pointer,
      :SDL_HasPrimarySelectionText => :bool,
      :SDL_SetClipboardData => :bool,
      :SDL_ClearClipboardData => :bool,
      :SDL_GetClipboardData => :pointer,
      :SDL_HasClipboardData => :bool,
      :SDL_GetClipboardMimeTypes => :pointer,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

