# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  PROP_GLOBAL_VIDEO_WAYLAND_WL_DISPLAY_POINTER = "SDL.video.wayland.wl_display"
  WINDOW_FULLSCREEN = 0x0000000000000001
  WINDOW_OPENGL = 0x0000000000000002
  WINDOW_OCCLUDED = 0x0000000000000004
  WINDOW_HIDDEN = 0x0000000000000008
  WINDOW_BORDERLESS = 0x0000000000000010
  WINDOW_RESIZABLE = 0x0000000000000020
  WINDOW_MINIMIZED = 0x0000000000000040
  WINDOW_MAXIMIZED = 0x0000000000000080
  WINDOW_MOUSE_GRABBED = 0x0000000000000100
  WINDOW_INPUT_FOCUS = 0x0000000000000200
  WINDOW_MOUSE_FOCUS = 0x0000000000000400
  WINDOW_EXTERNAL = 0x0000000000000800
  WINDOW_MODAL = 0x0000000000001000
  WINDOW_HIGH_PIXEL_DENSITY = 0x0000000000002000
  WINDOW_MOUSE_CAPTURE = 0x0000000000004000
  WINDOW_MOUSE_RELATIVE_MODE = 0x0000000000008000
  WINDOW_ALWAYS_ON_TOP = 0x0000000000010000
  WINDOW_UTILITY = 0x0000000000020000
  WINDOW_TOOLTIP = 0x0000000000040000
  WINDOW_POPUP_MENU = 0x0000000000080000
  WINDOW_KEYBOARD_GRABBED = 0x0000000000100000
  WINDOW_VULKAN = 0x0000000010000000
  WINDOW_METAL = 0x0000000020000000
  WINDOW_TRANSPARENT = 0x0000000040000000
  WINDOW_NOT_FOCUSABLE = 0x0000000080000000
  WINDOWPOS_UNDEFINED_MASK = 0x1FFF0000
  WINDOWPOS_CENTERED_MASK = 0x2FFF0000
  GL_CONTEXT_PROFILE_CORE = 0x0001
  GL_CONTEXT_PROFILE_COMPATIBILITY = 0x0002
  GL_CONTEXT_PROFILE_ES = 0x0004
  GL_CONTEXT_DEBUG_FLAG = 0x0001
  GL_CONTEXT_FORWARD_COMPATIBLE_FLAG = 0x0002
  GL_CONTEXT_ROBUST_ACCESS_FLAG = 0x0004
  GL_CONTEXT_RESET_ISOLATION_FLAG = 0x0008
  GL_CONTEXT_RELEASE_BEHAVIOR_NONE = 0x0000
  GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = 0x0001
  GL_CONTEXT_RESET_NO_NOTIFICATION = 0x0000
  GL_CONTEXT_RESET_LOSE_CONTEXT = 0x0001
  PROP_DISPLAY_HDR_ENABLED_BOOLEAN = "SDL.display.HDR_enabled"
  PROP_DISPLAY_KMSDRM_PANEL_ORIENTATION_NUMBER = "SDL.display.KMSDRM.panel_orientation"
  PROP_WINDOW_CREATE_ALWAYS_ON_TOP_BOOLEAN = "SDL.window.create.always_on_top"
  PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN = "SDL.window.create.borderless"
  PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN = "SDL.window.create.focusable"
  PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN = "SDL.window.create.external_graphics_context"
  PROP_WINDOW_CREATE_FLAGS_NUMBER = "SDL.window.create.flags"
  PROP_WINDOW_CREATE_FULLSCREEN_BOOLEAN = "SDL.window.create.fullscreen"
  PROP_WINDOW_CREATE_HEIGHT_NUMBER = "SDL.window.create.height"
  PROP_WINDOW_CREATE_HIDDEN_BOOLEAN = "SDL.window.create.hidden"
  PROP_WINDOW_CREATE_HIGH_PIXEL_DENSITY_BOOLEAN = "SDL.window.create.high_pixel_density"
  PROP_WINDOW_CREATE_MAXIMIZED_BOOLEAN = "SDL.window.create.maximized"
  PROP_WINDOW_CREATE_MENU_BOOLEAN = "SDL.window.create.menu"
  PROP_WINDOW_CREATE_METAL_BOOLEAN = "SDL.window.create.metal"
  PROP_WINDOW_CREATE_MINIMIZED_BOOLEAN = "SDL.window.create.minimized"
  PROP_WINDOW_CREATE_MODAL_BOOLEAN = "SDL.window.create.modal"
  PROP_WINDOW_CREATE_MOUSE_GRABBED_BOOLEAN = "SDL.window.create.mouse_grabbed"
  PROP_WINDOW_CREATE_OPENGL_BOOLEAN = "SDL.window.create.opengl"
  PROP_WINDOW_CREATE_PARENT_POINTER = "SDL.window.create.parent"
  PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN = "SDL.window.create.resizable"
  PROP_WINDOW_CREATE_TITLE_STRING = "SDL.window.create.title"
  PROP_WINDOW_CREATE_TRANSPARENT_BOOLEAN = "SDL.window.create.transparent"
  PROP_WINDOW_CREATE_TOOLTIP_BOOLEAN = "SDL.window.create.tooltip"
  PROP_WINDOW_CREATE_UTILITY_BOOLEAN = "SDL.window.create.utility"
  PROP_WINDOW_CREATE_VULKAN_BOOLEAN = "SDL.window.create.vulkan"
  PROP_WINDOW_CREATE_WIDTH_NUMBER = "SDL.window.create.width"
  PROP_WINDOW_CREATE_X_NUMBER = "SDL.window.create.x"
  PROP_WINDOW_CREATE_Y_NUMBER = "SDL.window.create.y"
  PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER = "SDL.window.create.cocoa.window"
  PROP_WINDOW_CREATE_COCOA_VIEW_POINTER = "SDL.window.create.cocoa.view"
  PROP_WINDOW_CREATE_WAYLAND_SURFACE_ROLE_CUSTOM_BOOLEAN = "SDL.window.create.wayland.surface_role_custom"
  PROP_WINDOW_CREATE_WAYLAND_CREATE_EGL_WINDOW_BOOLEAN = "SDL.window.create.wayland.create_egl_window"
  PROP_WINDOW_CREATE_WAYLAND_WL_SURFACE_POINTER = "SDL.window.create.wayland.wl_surface"
  PROP_WINDOW_CREATE_WIN32_HWND_POINTER = "SDL.window.create.win32.hwnd"
  PROP_WINDOW_CREATE_WIN32_PIXEL_FORMAT_HWND_POINTER = "SDL.window.create.win32.pixel_format_hwnd"
  PROP_WINDOW_CREATE_X11_WINDOW_NUMBER = "SDL.window.create.x11.window"
  PROP_WINDOW_SHAPE_POINTER = "SDL.window.shape"
  PROP_WINDOW_HDR_ENABLED_BOOLEAN = "SDL.window.HDR_enabled"
  PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT = "SDL.window.SDR_white_level"
  PROP_WINDOW_HDR_HEADROOM_FLOAT = "SDL.window.HDR_headroom"
  PROP_WINDOW_ANDROID_WINDOW_POINTER = "SDL.window.android.window"
  PROP_WINDOW_ANDROID_SURFACE_POINTER = "SDL.window.android.surface"
  PROP_WINDOW_UIKIT_WINDOW_POINTER = "SDL.window.uikit.window"
  PROP_WINDOW_UIKIT_METAL_VIEW_TAG_NUMBER = "SDL.window.uikit.metal_view_tag"
  PROP_WINDOW_UIKIT_OPENGL_FRAMEBUFFER_NUMBER = "SDL.window.uikit.opengl.framebuffer"
  PROP_WINDOW_UIKIT_OPENGL_RENDERBUFFER_NUMBER = "SDL.window.uikit.opengl.renderbuffer"
  PROP_WINDOW_UIKIT_OPENGL_RESOLVE_FRAMEBUFFER_NUMBER = "SDL.window.uikit.opengl.resolve_framebuffer"
  PROP_WINDOW_KMSDRM_DEVICE_INDEX_NUMBER = "SDL.window.kmsdrm.dev_index"
  PROP_WINDOW_KMSDRM_DRM_FD_NUMBER = "SDL.window.kmsdrm.drm_fd"
  PROP_WINDOW_KMSDRM_GBM_DEVICE_POINTER = "SDL.window.kmsdrm.gbm_dev"
  PROP_WINDOW_COCOA_WINDOW_POINTER = "SDL.window.cocoa.window"
  PROP_WINDOW_COCOA_METAL_VIEW_TAG_NUMBER = "SDL.window.cocoa.metal_view_tag"
  PROP_WINDOW_OPENVR_OVERLAY_ID = "SDL.window.openvr.overlay_id"
  PROP_WINDOW_VIVANTE_DISPLAY_POINTER = "SDL.window.vivante.display"
  PROP_WINDOW_VIVANTE_WINDOW_POINTER = "SDL.window.vivante.window"
  PROP_WINDOW_VIVANTE_SURFACE_POINTER = "SDL.window.vivante.surface"
  PROP_WINDOW_WIN32_HWND_POINTER = "SDL.window.win32.hwnd"
  PROP_WINDOW_WIN32_HDC_POINTER = "SDL.window.win32.hdc"
  PROP_WINDOW_WIN32_INSTANCE_POINTER = "SDL.window.win32.instance"
  PROP_WINDOW_WAYLAND_DISPLAY_POINTER = "SDL.window.wayland.display"
  PROP_WINDOW_WAYLAND_SURFACE_POINTER = "SDL.window.wayland.surface"
  PROP_WINDOW_WAYLAND_VIEWPORT_POINTER = "SDL.window.wayland.viewport"
  PROP_WINDOW_WAYLAND_EGL_WINDOW_POINTER = "SDL.window.wayland.egl_window"
  PROP_WINDOW_WAYLAND_XDG_SURFACE_POINTER = "SDL.window.wayland.xdg_surface"
  PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_POINTER = "SDL.window.wayland.xdg_toplevel"
  PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_EXPORT_HANDLE_STRING = "SDL.window.wayland.xdg_toplevel_export_handle"
  PROP_WINDOW_WAYLAND_XDG_POPUP_POINTER = "SDL.window.wayland.xdg_popup"
  PROP_WINDOW_WAYLAND_XDG_POSITIONER_POINTER = "SDL.window.wayland.xdg_positioner"
  PROP_WINDOW_X11_DISPLAY_POINTER = "SDL.window.x11.display"
  PROP_WINDOW_X11_SCREEN_NUMBER = "SDL.window.x11.screen"
  PROP_WINDOW_X11_WINDOW_NUMBER = "SDL.window.x11.window"
  WINDOW_SURFACE_VSYNC_DISABLED = 0
  WINDOW_SURFACE_VSYNC_ADAPTIVE = -1

  # Enum

  SYSTEM_THEME_UNKNOWN = 0
  SYSTEM_THEME_LIGHT = 1
  SYSTEM_THEME_DARK = 2
  ORIENTATION_UNKNOWN = 0
  ORIENTATION_LANDSCAPE = 1
  ORIENTATION_LANDSCAPE_FLIPPED = 2
  ORIENTATION_PORTRAIT = 3
  ORIENTATION_PORTRAIT_FLIPPED = 4
  FLASH_CANCEL = 0
  FLASH_BRIEFLY = 1
  FLASH_UNTIL_FOCUSED = 2
  GL_RED_SIZE = 0
  GL_GREEN_SIZE = 1
  GL_BLUE_SIZE = 2
  GL_ALPHA_SIZE = 3
  GL_BUFFER_SIZE = 4
  GL_DOUBLEBUFFER = 5
  GL_DEPTH_SIZE = 6
  GL_STENCIL_SIZE = 7
  GL_ACCUM_RED_SIZE = 8
  GL_ACCUM_GREEN_SIZE = 9
  GL_ACCUM_BLUE_SIZE = 10
  GL_ACCUM_ALPHA_SIZE = 11
  GL_STEREO = 12
  GL_MULTISAMPLEBUFFERS = 13
  GL_MULTISAMPLESAMPLES = 14
  GL_ACCELERATED_VISUAL = 15
  GL_RETAINED_BACKING = 16
  GL_CONTEXT_MAJOR_VERSION = 17
  GL_CONTEXT_MINOR_VERSION = 18
  GL_CONTEXT_FLAGS = 19
  GL_CONTEXT_PROFILE_MASK = 20
  GL_SHARE_WITH_CURRENT_CONTEXT = 21
  GL_FRAMEBUFFER_SRGB_CAPABLE = 22
  GL_CONTEXT_RELEASE_BEHAVIOR = 23
  GL_CONTEXT_RESET_NOTIFICATION = 24
  GL_CONTEXT_NO_ERROR = 25
  GL_FLOATBUFFERS = 26
  GL_EGL_PLATFORM = 27
  HITTEST_NORMAL = 0
  HITTEST_DRAGGABLE = 1
  HITTEST_RESIZE_TOPLEFT = 2
  HITTEST_RESIZE_TOP = 3
  HITTEST_RESIZE_TOPRIGHT = 4
  HITTEST_RESIZE_RIGHT = 5
  HITTEST_RESIZE_BOTTOMRIGHT = 6
  HITTEST_RESIZE_BOTTOM = 7
  HITTEST_RESIZE_BOTTOMLEFT = 8
  HITTEST_RESIZE_LEFT = 9

  # Typedef

  typedef :uint, :SDL_DisplayID
  typedef :uint, :SDL_WindowID
  typedef :int, :SDL_SystemTheme
  typedef :int, :SDL_DisplayOrientation
  typedef :ulong_long, :SDL_WindowFlags
  typedef :int, :SDL_FlashOperation
  typedef :pointer, :SDL_GLContext
  typedef :pointer, :SDL_EGLDisplay
  typedef :pointer, :SDL_EGLConfig
  typedef :pointer, :SDL_EGLSurface
  typedef :long_long, :SDL_EGLAttrib
  typedef :int, :SDL_EGLint
  callback :SDL_EGLAttribArrayCallback, [:pointer], :pointer
  callback :SDL_EGLIntArrayCallback, [:pointer, :pointer, :pointer], :pointer
  typedef :int, :SDL_GLAttr
  typedef :uint, :SDL_GLProfile
  typedef :uint, :SDL_GLContextFlag
  typedef :uint, :SDL_GLContextReleaseFlag
  typedef :uint, :SDL_GLContextResetNotification
  typedef :int, :SDL_HitTestResult
  callback :SDL_HitTest, [:pointer, :pointer, :pointer], :int

  # Struct

  class DisplayMode < FFI::Struct
    layout(
      :displayID, :uint,
      :format, :int,
      :w, :int,
      :h, :int,
      :pixel_density, :float,
      :refresh_rate, :float,
      :refresh_rate_numerator, :int,
      :refresh_rate_denominator, :int,
      :internal, :pointer,
    )
  end


  # Function

  def self.setup_video_symbols(output_error = false)
    symbols = [
      :SDL_GetNumVideoDrivers,
      :SDL_GetVideoDriver,
      :SDL_GetCurrentVideoDriver,
      :SDL_GetSystemTheme,
      :SDL_GetDisplays,
      :SDL_GetPrimaryDisplay,
      :SDL_GetDisplayProperties,
      :SDL_GetDisplayName,
      :SDL_GetDisplayBounds,
      :SDL_GetDisplayUsableBounds,
      :SDL_GetNaturalDisplayOrientation,
      :SDL_GetCurrentDisplayOrientation,
      :SDL_GetDisplayContentScale,
      :SDL_GetFullscreenDisplayModes,
      :SDL_GetClosestFullscreenDisplayMode,
      :SDL_GetDesktopDisplayMode,
      :SDL_GetCurrentDisplayMode,
      :SDL_GetDisplayForPoint,
      :SDL_GetDisplayForRect,
      :SDL_GetDisplayForWindow,
      :SDL_GetWindowPixelDensity,
      :SDL_GetWindowDisplayScale,
      :SDL_SetWindowFullscreenMode,
      :SDL_GetWindowFullscreenMode,
      :SDL_GetWindowICCProfile,
      :SDL_GetWindowPixelFormat,
      :SDL_GetWindows,
      :SDL_CreateWindow,
      :SDL_CreatePopupWindow,
      :SDL_CreateWindowWithProperties,
      :SDL_GetWindowID,
      :SDL_GetWindowFromID,
      :SDL_GetWindowParent,
      :SDL_GetWindowProperties,
      :SDL_GetWindowFlags,
      :SDL_SetWindowTitle,
      :SDL_GetWindowTitle,
      :SDL_SetWindowIcon,
      :SDL_SetWindowPosition,
      :SDL_GetWindowPosition,
      :SDL_SetWindowSize,
      :SDL_GetWindowSize,
      :SDL_GetWindowSafeArea,
      :SDL_SetWindowAspectRatio,
      :SDL_GetWindowAspectRatio,
      :SDL_GetWindowBordersSize,
      :SDL_GetWindowSizeInPixels,
      :SDL_SetWindowMinimumSize,
      :SDL_GetWindowMinimumSize,
      :SDL_SetWindowMaximumSize,
      :SDL_GetWindowMaximumSize,
      :SDL_SetWindowBordered,
      :SDL_SetWindowResizable,
      :SDL_SetWindowAlwaysOnTop,
      :SDL_ShowWindow,
      :SDL_HideWindow,
      :SDL_RaiseWindow,
      :SDL_MaximizeWindow,
      :SDL_MinimizeWindow,
      :SDL_RestoreWindow,
      :SDL_SetWindowFullscreen,
      :SDL_SyncWindow,
      :SDL_WindowHasSurface,
      :SDL_GetWindowSurface,
      :SDL_SetWindowSurfaceVSync,
      :SDL_GetWindowSurfaceVSync,
      :SDL_UpdateWindowSurface,
      :SDL_UpdateWindowSurfaceRects,
      :SDL_DestroyWindowSurface,
      :SDL_SetWindowKeyboardGrab,
      :SDL_SetWindowMouseGrab,
      :SDL_GetWindowKeyboardGrab,
      :SDL_GetWindowMouseGrab,
      :SDL_GetGrabbedWindow,
      :SDL_SetWindowMouseRect,
      :SDL_GetWindowMouseRect,
      :SDL_SetWindowOpacity,
      :SDL_GetWindowOpacity,
      :SDL_SetWindowParent,
      :SDL_SetWindowModal,
      :SDL_SetWindowFocusable,
      :SDL_ShowWindowSystemMenu,
      :SDL_SetWindowHitTest,
      :SDL_SetWindowShape,
      :SDL_FlashWindow,
      :SDL_DestroyWindow,
      :SDL_ScreenSaverEnabled,
      :SDL_EnableScreenSaver,
      :SDL_DisableScreenSaver,
      :SDL_GL_LoadLibrary,
      :SDL_GL_GetProcAddress,
      :SDL_EGL_GetProcAddress,
      :SDL_GL_UnloadLibrary,
      :SDL_GL_ExtensionSupported,
      :SDL_GL_ResetAttributes,
      :SDL_GL_SetAttribute,
      :SDL_GL_GetAttribute,
      :SDL_GL_CreateContext,
      :SDL_GL_MakeCurrent,
      :SDL_GL_GetCurrentWindow,
      :SDL_GL_GetCurrentContext,
      :SDL_EGL_GetCurrentDisplay,
      :SDL_EGL_GetCurrentConfig,
      :SDL_EGL_GetWindowSurface,
      :SDL_EGL_SetAttributeCallbacks,
      :SDL_GL_SetSwapInterval,
      :SDL_GL_GetSwapInterval,
      :SDL_GL_SwapWindow,
      :SDL_GL_DestroyContext,
    ]
    apis = {
      :SDL_GetNumVideoDrivers => :GetNumVideoDrivers,
      :SDL_GetVideoDriver => :GetVideoDriver,
      :SDL_GetCurrentVideoDriver => :GetCurrentVideoDriver,
      :SDL_GetSystemTheme => :GetSystemTheme,
      :SDL_GetDisplays => :GetDisplays,
      :SDL_GetPrimaryDisplay => :GetPrimaryDisplay,
      :SDL_GetDisplayProperties => :GetDisplayProperties,
      :SDL_GetDisplayName => :GetDisplayName,
      :SDL_GetDisplayBounds => :GetDisplayBounds,
      :SDL_GetDisplayUsableBounds => :GetDisplayUsableBounds,
      :SDL_GetNaturalDisplayOrientation => :GetNaturalDisplayOrientation,
      :SDL_GetCurrentDisplayOrientation => :GetCurrentDisplayOrientation,
      :SDL_GetDisplayContentScale => :GetDisplayContentScale,
      :SDL_GetFullscreenDisplayModes => :GetFullscreenDisplayModes,
      :SDL_GetClosestFullscreenDisplayMode => :GetClosestFullscreenDisplayMode,
      :SDL_GetDesktopDisplayMode => :GetDesktopDisplayMode,
      :SDL_GetCurrentDisplayMode => :GetCurrentDisplayMode,
      :SDL_GetDisplayForPoint => :GetDisplayForPoint,
      :SDL_GetDisplayForRect => :GetDisplayForRect,
      :SDL_GetDisplayForWindow => :GetDisplayForWindow,
      :SDL_GetWindowPixelDensity => :GetWindowPixelDensity,
      :SDL_GetWindowDisplayScale => :GetWindowDisplayScale,
      :SDL_SetWindowFullscreenMode => :SetWindowFullscreenMode,
      :SDL_GetWindowFullscreenMode => :GetWindowFullscreenMode,
      :SDL_GetWindowICCProfile => :GetWindowICCProfile,
      :SDL_GetWindowPixelFormat => :GetWindowPixelFormat,
      :SDL_GetWindows => :GetWindows,
      :SDL_CreateWindow => :CreateWindow,
      :SDL_CreatePopupWindow => :CreatePopupWindow,
      :SDL_CreateWindowWithProperties => :CreateWindowWithProperties,
      :SDL_GetWindowID => :GetWindowID,
      :SDL_GetWindowFromID => :GetWindowFromID,
      :SDL_GetWindowParent => :GetWindowParent,
      :SDL_GetWindowProperties => :GetWindowProperties,
      :SDL_GetWindowFlags => :GetWindowFlags,
      :SDL_SetWindowTitle => :SetWindowTitle,
      :SDL_GetWindowTitle => :GetWindowTitle,
      :SDL_SetWindowIcon => :SetWindowIcon,
      :SDL_SetWindowPosition => :SetWindowPosition,
      :SDL_GetWindowPosition => :GetWindowPosition,
      :SDL_SetWindowSize => :SetWindowSize,
      :SDL_GetWindowSize => :GetWindowSize,
      :SDL_GetWindowSafeArea => :GetWindowSafeArea,
      :SDL_SetWindowAspectRatio => :SetWindowAspectRatio,
      :SDL_GetWindowAspectRatio => :GetWindowAspectRatio,
      :SDL_GetWindowBordersSize => :GetWindowBordersSize,
      :SDL_GetWindowSizeInPixels => :GetWindowSizeInPixels,
      :SDL_SetWindowMinimumSize => :SetWindowMinimumSize,
      :SDL_GetWindowMinimumSize => :GetWindowMinimumSize,
      :SDL_SetWindowMaximumSize => :SetWindowMaximumSize,
      :SDL_GetWindowMaximumSize => :GetWindowMaximumSize,
      :SDL_SetWindowBordered => :SetWindowBordered,
      :SDL_SetWindowResizable => :SetWindowResizable,
      :SDL_SetWindowAlwaysOnTop => :SetWindowAlwaysOnTop,
      :SDL_ShowWindow => :ShowWindow,
      :SDL_HideWindow => :HideWindow,
      :SDL_RaiseWindow => :RaiseWindow,
      :SDL_MaximizeWindow => :MaximizeWindow,
      :SDL_MinimizeWindow => :MinimizeWindow,
      :SDL_RestoreWindow => :RestoreWindow,
      :SDL_SetWindowFullscreen => :SetWindowFullscreen,
      :SDL_SyncWindow => :SyncWindow,
      :SDL_WindowHasSurface => :WindowHasSurface,
      :SDL_GetWindowSurface => :GetWindowSurface,
      :SDL_SetWindowSurfaceVSync => :SetWindowSurfaceVSync,
      :SDL_GetWindowSurfaceVSync => :GetWindowSurfaceVSync,
      :SDL_UpdateWindowSurface => :UpdateWindowSurface,
      :SDL_UpdateWindowSurfaceRects => :UpdateWindowSurfaceRects,
      :SDL_DestroyWindowSurface => :DestroyWindowSurface,
      :SDL_SetWindowKeyboardGrab => :SetWindowKeyboardGrab,
      :SDL_SetWindowMouseGrab => :SetWindowMouseGrab,
      :SDL_GetWindowKeyboardGrab => :GetWindowKeyboardGrab,
      :SDL_GetWindowMouseGrab => :GetWindowMouseGrab,
      :SDL_GetGrabbedWindow => :GetGrabbedWindow,
      :SDL_SetWindowMouseRect => :SetWindowMouseRect,
      :SDL_GetWindowMouseRect => :GetWindowMouseRect,
      :SDL_SetWindowOpacity => :SetWindowOpacity,
      :SDL_GetWindowOpacity => :GetWindowOpacity,
      :SDL_SetWindowParent => :SetWindowParent,
      :SDL_SetWindowModal => :SetWindowModal,
      :SDL_SetWindowFocusable => :SetWindowFocusable,
      :SDL_ShowWindowSystemMenu => :ShowWindowSystemMenu,
      :SDL_SetWindowHitTest => :SetWindowHitTest,
      :SDL_SetWindowShape => :SetWindowShape,
      :SDL_FlashWindow => :FlashWindow,
      :SDL_DestroyWindow => :DestroyWindow,
      :SDL_ScreenSaverEnabled => :ScreenSaverEnabled,
      :SDL_EnableScreenSaver => :EnableScreenSaver,
      :SDL_DisableScreenSaver => :DisableScreenSaver,
      :SDL_GL_LoadLibrary => :GL_LoadLibrary,
      :SDL_GL_GetProcAddress => :GL_GetProcAddress,
      :SDL_EGL_GetProcAddress => :EGL_GetProcAddress,
      :SDL_GL_UnloadLibrary => :GL_UnloadLibrary,
      :SDL_GL_ExtensionSupported => :GL_ExtensionSupported,
      :SDL_GL_ResetAttributes => :GL_ResetAttributes,
      :SDL_GL_SetAttribute => :GL_SetAttribute,
      :SDL_GL_GetAttribute => :GL_GetAttribute,
      :SDL_GL_CreateContext => :GL_CreateContext,
      :SDL_GL_MakeCurrent => :GL_MakeCurrent,
      :SDL_GL_GetCurrentWindow => :GL_GetCurrentWindow,
      :SDL_GL_GetCurrentContext => :GL_GetCurrentContext,
      :SDL_EGL_GetCurrentDisplay => :EGL_GetCurrentDisplay,
      :SDL_EGL_GetCurrentConfig => :EGL_GetCurrentConfig,
      :SDL_EGL_GetWindowSurface => :EGL_GetWindowSurface,
      :SDL_EGL_SetAttributeCallbacks => :EGL_SetAttributeCallbacks,
      :SDL_GL_SetSwapInterval => :GL_SetSwapInterval,
      :SDL_GL_GetSwapInterval => :GL_GetSwapInterval,
      :SDL_GL_SwapWindow => :GL_SwapWindow,
      :SDL_GL_DestroyContext => :GL_DestroyContext,
    }
    args = {
      :SDL_GetNumVideoDrivers => [],
      :SDL_GetVideoDriver => [:int],
      :SDL_GetCurrentVideoDriver => [],
      :SDL_GetSystemTheme => [],
      :SDL_GetDisplays => [:pointer],
      :SDL_GetPrimaryDisplay => [],
      :SDL_GetDisplayProperties => [:uint],
      :SDL_GetDisplayName => [:uint],
      :SDL_GetDisplayBounds => [:uint, :pointer],
      :SDL_GetDisplayUsableBounds => [:uint, :pointer],
      :SDL_GetNaturalDisplayOrientation => [:uint],
      :SDL_GetCurrentDisplayOrientation => [:uint],
      :SDL_GetDisplayContentScale => [:uint],
      :SDL_GetFullscreenDisplayModes => [:uint, :pointer],
      :SDL_GetClosestFullscreenDisplayMode => [:uint, :int, :int, :float, :bool, :pointer],
      :SDL_GetDesktopDisplayMode => [:uint],
      :SDL_GetCurrentDisplayMode => [:uint],
      :SDL_GetDisplayForPoint => [:pointer],
      :SDL_GetDisplayForRect => [:pointer],
      :SDL_GetDisplayForWindow => [:pointer],
      :SDL_GetWindowPixelDensity => [:pointer],
      :SDL_GetWindowDisplayScale => [:pointer],
      :SDL_SetWindowFullscreenMode => [:pointer, :pointer],
      :SDL_GetWindowFullscreenMode => [:pointer],
      :SDL_GetWindowICCProfile => [:pointer, :pointer],
      :SDL_GetWindowPixelFormat => [:pointer],
      :SDL_GetWindows => [:pointer],
      :SDL_CreateWindow => [:pointer, :int, :int, :ulong_long],
      :SDL_CreatePopupWindow => [:pointer, :int, :int, :int, :int, :ulong_long],
      :SDL_CreateWindowWithProperties => [:uint],
      :SDL_GetWindowID => [:pointer],
      :SDL_GetWindowFromID => [:uint],
      :SDL_GetWindowParent => [:pointer],
      :SDL_GetWindowProperties => [:pointer],
      :SDL_GetWindowFlags => [:pointer],
      :SDL_SetWindowTitle => [:pointer, :pointer],
      :SDL_GetWindowTitle => [:pointer],
      :SDL_SetWindowIcon => [:pointer, :pointer],
      :SDL_SetWindowPosition => [:pointer, :int, :int],
      :SDL_GetWindowPosition => [:pointer, :pointer, :pointer],
      :SDL_SetWindowSize => [:pointer, :int, :int],
      :SDL_GetWindowSize => [:pointer, :pointer, :pointer],
      :SDL_GetWindowSafeArea => [:pointer, :pointer],
      :SDL_SetWindowAspectRatio => [:pointer, :float, :float],
      :SDL_GetWindowAspectRatio => [:pointer, :pointer, :pointer],
      :SDL_GetWindowBordersSize => [:pointer, :pointer, :pointer, :pointer, :pointer],
      :SDL_GetWindowSizeInPixels => [:pointer, :pointer, :pointer],
      :SDL_SetWindowMinimumSize => [:pointer, :int, :int],
      :SDL_GetWindowMinimumSize => [:pointer, :pointer, :pointer],
      :SDL_SetWindowMaximumSize => [:pointer, :int, :int],
      :SDL_GetWindowMaximumSize => [:pointer, :pointer, :pointer],
      :SDL_SetWindowBordered => [:pointer, :bool],
      :SDL_SetWindowResizable => [:pointer, :bool],
      :SDL_SetWindowAlwaysOnTop => [:pointer, :bool],
      :SDL_ShowWindow => [:pointer],
      :SDL_HideWindow => [:pointer],
      :SDL_RaiseWindow => [:pointer],
      :SDL_MaximizeWindow => [:pointer],
      :SDL_MinimizeWindow => [:pointer],
      :SDL_RestoreWindow => [:pointer],
      :SDL_SetWindowFullscreen => [:pointer, :bool],
      :SDL_SyncWindow => [:pointer],
      :SDL_WindowHasSurface => [:pointer],
      :SDL_GetWindowSurface => [:pointer],
      :SDL_SetWindowSurfaceVSync => [:pointer, :int],
      :SDL_GetWindowSurfaceVSync => [:pointer, :pointer],
      :SDL_UpdateWindowSurface => [:pointer],
      :SDL_UpdateWindowSurfaceRects => [:pointer, :pointer, :int],
      :SDL_DestroyWindowSurface => [:pointer],
      :SDL_SetWindowKeyboardGrab => [:pointer, :bool],
      :SDL_SetWindowMouseGrab => [:pointer, :bool],
      :SDL_GetWindowKeyboardGrab => [:pointer],
      :SDL_GetWindowMouseGrab => [:pointer],
      :SDL_GetGrabbedWindow => [],
      :SDL_SetWindowMouseRect => [:pointer, :pointer],
      :SDL_GetWindowMouseRect => [:pointer],
      :SDL_SetWindowOpacity => [:pointer, :float],
      :SDL_GetWindowOpacity => [:pointer],
      :SDL_SetWindowParent => [:pointer, :pointer],
      :SDL_SetWindowModal => [:pointer, :bool],
      :SDL_SetWindowFocusable => [:pointer, :bool],
      :SDL_ShowWindowSystemMenu => [:pointer, :int, :int],
      :SDL_SetWindowHitTest => [:pointer, :SDL_HitTest, :pointer],
      :SDL_SetWindowShape => [:pointer, :pointer],
      :SDL_FlashWindow => [:pointer, :int],
      :SDL_DestroyWindow => [:pointer],
      :SDL_ScreenSaverEnabled => [],
      :SDL_EnableScreenSaver => [],
      :SDL_DisableScreenSaver => [],
      :SDL_GL_LoadLibrary => [:pointer],
      :SDL_GL_GetProcAddress => [:pointer],
      :SDL_EGL_GetProcAddress => [:pointer],
      :SDL_GL_UnloadLibrary => [],
      :SDL_GL_ExtensionSupported => [:pointer],
      :SDL_GL_ResetAttributes => [],
      :SDL_GL_SetAttribute => [:int, :int],
      :SDL_GL_GetAttribute => [:int, :pointer],
      :SDL_GL_CreateContext => [:pointer],
      :SDL_GL_MakeCurrent => [:pointer, :pointer],
      :SDL_GL_GetCurrentWindow => [],
      :SDL_GL_GetCurrentContext => [],
      :SDL_EGL_GetCurrentDisplay => [],
      :SDL_EGL_GetCurrentConfig => [],
      :SDL_EGL_GetWindowSurface => [:pointer],
      :SDL_EGL_SetAttributeCallbacks => [:SDL_EGLAttribArrayCallback, :SDL_EGLIntArrayCallback, :SDL_EGLIntArrayCallback, :pointer],
      :SDL_GL_SetSwapInterval => [:int],
      :SDL_GL_GetSwapInterval => [:pointer],
      :SDL_GL_SwapWindow => [:pointer],
      :SDL_GL_DestroyContext => [:pointer],
    }
    retvals = {
      :SDL_GetNumVideoDrivers => :int,
      :SDL_GetVideoDriver => :pointer,
      :SDL_GetCurrentVideoDriver => :pointer,
      :SDL_GetSystemTheme => :int,
      :SDL_GetDisplays => :pointer,
      :SDL_GetPrimaryDisplay => :uint,
      :SDL_GetDisplayProperties => :uint,
      :SDL_GetDisplayName => :pointer,
      :SDL_GetDisplayBounds => :bool,
      :SDL_GetDisplayUsableBounds => :bool,
      :SDL_GetNaturalDisplayOrientation => :int,
      :SDL_GetCurrentDisplayOrientation => :int,
      :SDL_GetDisplayContentScale => :float,
      :SDL_GetFullscreenDisplayModes => :pointer,
      :SDL_GetClosestFullscreenDisplayMode => :bool,
      :SDL_GetDesktopDisplayMode => :pointer,
      :SDL_GetCurrentDisplayMode => :pointer,
      :SDL_GetDisplayForPoint => :uint,
      :SDL_GetDisplayForRect => :uint,
      :SDL_GetDisplayForWindow => :uint,
      :SDL_GetWindowPixelDensity => :float,
      :SDL_GetWindowDisplayScale => :float,
      :SDL_SetWindowFullscreenMode => :bool,
      :SDL_GetWindowFullscreenMode => :pointer,
      :SDL_GetWindowICCProfile => :pointer,
      :SDL_GetWindowPixelFormat => :int,
      :SDL_GetWindows => :pointer,
      :SDL_CreateWindow => :pointer,
      :SDL_CreatePopupWindow => :pointer,
      :SDL_CreateWindowWithProperties => :pointer,
      :SDL_GetWindowID => :uint,
      :SDL_GetWindowFromID => :pointer,
      :SDL_GetWindowParent => :pointer,
      :SDL_GetWindowProperties => :uint,
      :SDL_GetWindowFlags => :ulong_long,
      :SDL_SetWindowTitle => :bool,
      :SDL_GetWindowTitle => :pointer,
      :SDL_SetWindowIcon => :bool,
      :SDL_SetWindowPosition => :bool,
      :SDL_GetWindowPosition => :bool,
      :SDL_SetWindowSize => :bool,
      :SDL_GetWindowSize => :bool,
      :SDL_GetWindowSafeArea => :bool,
      :SDL_SetWindowAspectRatio => :bool,
      :SDL_GetWindowAspectRatio => :bool,
      :SDL_GetWindowBordersSize => :bool,
      :SDL_GetWindowSizeInPixels => :bool,
      :SDL_SetWindowMinimumSize => :bool,
      :SDL_GetWindowMinimumSize => :bool,
      :SDL_SetWindowMaximumSize => :bool,
      :SDL_GetWindowMaximumSize => :bool,
      :SDL_SetWindowBordered => :bool,
      :SDL_SetWindowResizable => :bool,
      :SDL_SetWindowAlwaysOnTop => :bool,
      :SDL_ShowWindow => :bool,
      :SDL_HideWindow => :bool,
      :SDL_RaiseWindow => :bool,
      :SDL_MaximizeWindow => :bool,
      :SDL_MinimizeWindow => :bool,
      :SDL_RestoreWindow => :bool,
      :SDL_SetWindowFullscreen => :bool,
      :SDL_SyncWindow => :bool,
      :SDL_WindowHasSurface => :bool,
      :SDL_GetWindowSurface => :pointer,
      :SDL_SetWindowSurfaceVSync => :bool,
      :SDL_GetWindowSurfaceVSync => :bool,
      :SDL_UpdateWindowSurface => :bool,
      :SDL_UpdateWindowSurfaceRects => :bool,
      :SDL_DestroyWindowSurface => :bool,
      :SDL_SetWindowKeyboardGrab => :bool,
      :SDL_SetWindowMouseGrab => :bool,
      :SDL_GetWindowKeyboardGrab => :bool,
      :SDL_GetWindowMouseGrab => :bool,
      :SDL_GetGrabbedWindow => :pointer,
      :SDL_SetWindowMouseRect => :bool,
      :SDL_GetWindowMouseRect => :pointer,
      :SDL_SetWindowOpacity => :bool,
      :SDL_GetWindowOpacity => :float,
      :SDL_SetWindowParent => :bool,
      :SDL_SetWindowModal => :bool,
      :SDL_SetWindowFocusable => :bool,
      :SDL_ShowWindowSystemMenu => :bool,
      :SDL_SetWindowHitTest => :bool,
      :SDL_SetWindowShape => :bool,
      :SDL_FlashWindow => :bool,
      :SDL_DestroyWindow => :void,
      :SDL_ScreenSaverEnabled => :bool,
      :SDL_EnableScreenSaver => :bool,
      :SDL_DisableScreenSaver => :bool,
      :SDL_GL_LoadLibrary => :bool,
      :SDL_GL_GetProcAddress => :pointer,
      :SDL_EGL_GetProcAddress => :pointer,
      :SDL_GL_UnloadLibrary => :void,
      :SDL_GL_ExtensionSupported => :bool,
      :SDL_GL_ResetAttributes => :void,
      :SDL_GL_SetAttribute => :bool,
      :SDL_GL_GetAttribute => :bool,
      :SDL_GL_CreateContext => :pointer,
      :SDL_GL_MakeCurrent => :bool,
      :SDL_GL_GetCurrentWindow => :pointer,
      :SDL_GL_GetCurrentContext => :pointer,
      :SDL_EGL_GetCurrentDisplay => :pointer,
      :SDL_EGL_GetCurrentConfig => :pointer,
      :SDL_EGL_GetWindowSurface => :pointer,
      :SDL_EGL_SetAttributeCallbacks => :void,
      :SDL_GL_SetSwapInterval => :bool,
      :SDL_GL_GetSwapInterval => :bool,
      :SDL_GL_SwapWindow => :bool,
      :SDL_GL_DestroyContext => :bool,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

