# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro


  # Enum


  # Typedef


  # Struct


  # Function

  def self.setup_error_symbols(output_error = false)
    symbols = [
      :SDL_SetError,
      :SDL_SetErrorV,
      :SDL_OutOfMemory,
      :SDL_GetError,
      :SDL_ClearError,
    ]
    apis = {
      :SDL_SetError => :SetError,
      :SDL_SetErrorV => :SetErrorV,
      :SDL_OutOfMemory => :OutOfMemory,
      :SDL_GetError => :GetError,
      :SDL_ClearError => :ClearError,
    }
    args = {
      :SDL_SetError => [:pointer],
      :SDL_SetErrorV => [:pointer, :pointer],
      :SDL_OutOfMemory => [],
      :SDL_GetError => [],
      :SDL_ClearError => [],
    }
    retvals = {
      :SDL_SetError => :bool,
      :SDL_SetErrorV => :bool,
      :SDL_OutOfMemory => :bool,
      :SDL_GetError => :pointer,
      :SDL_ClearError => :bool,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

