# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro


  # Enum


  # Typedef


  # Struct

  class GUID < FFI::Struct
    layout(
      :data, [:uchar, 16],
    )
  end


  # Function

  def self.setup_guid_symbols(output_error = false)
    symbols = [
      :SDL_GUIDToString,
      :SDL_StringToGUID,
    ]
    apis = {
      :SDL_GUIDToString => :GUIDToString,
      :SDL_StringToGUID => :StringToGUID,
    }
    args = {
      :SDL_GUIDToString => [GUID.by_value, :pointer, :int],
      :SDL_StringToGUID => [:pointer],
    }
    retvals = {
      :SDL_GUIDToString => :void,
      :SDL_StringToGUID => GUID.by_value,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

