# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  MAJOR_VERSION = 3
  MINOR_VERSION = 2
  MICRO_VERSION = 0

  # Enum


  # Typedef


  # Struct


  # Function

  def self.setup_version_symbols(output_error = false)
    symbols = [
      :SDL_GetVersion,
      :SDL_GetRevision,
    ]
    apis = {
      :SDL_GetVersion => :GetVersion,
      :SDL_GetRevision => :GetRevision,
    }
    args = {
      :SDL_GetVersion => [],
      :SDL_GetRevision => [],
    }
    retvals = {
      :SDL_GetVersion => :int,
      :SDL_GetRevision => :pointer,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

