# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  AUDIO_MASK_BITSIZE = 0xFF
  AUDIO_MASK_SIGNED = 1 << 15

  # Enum

  AUDIO_UNKNOWN = 0
  AUDIO_U8 = 8
  AUDIO_S8 = 32776
  AUDIO_S16LE = 32784
  AUDIO_S16BE = 36880
  AUDIO_S32LE = 32800
  AUDIO_S32BE = 36896
  AUDIO_F32LE = 33056
  AUDIO_F32BE = 37152
  AUDIO_S16 = 32784
  AUDIO_S32 = 32800
  AUDIO_F32 = 33056

  # Typedef

  typedef :int, :SDL_AudioFormat
  typedef :uint, :SDL_AudioDeviceID
  callback :SDL_AudioStreamCallback, [:pointer, :pointer, :int, :int], :void
  callback :SDL_AudioPostmixCallback, [:pointer, :pointer, :pointer, :int], :void

  # Struct

  class AudioSpec < FFI::Struct
    layout(
      :format, :int,
      :channels, :int,
      :freq, :int,
    )
  end


  # Function

  def self.setup_audio_symbols(output_error = false)
    symbols = [
      :SDL_GetNumAudioDrivers,
      :SDL_GetAudioDriver,
      :SDL_GetCurrentAudioDriver,
      :SDL_GetAudioPlaybackDevices,
      :SDL_GetAudioRecordingDevices,
      :SDL_GetAudioDeviceName,
      :SDL_GetAudioDeviceFormat,
      :SDL_GetAudioDeviceChannelMap,
      :SDL_OpenAudioDevice,
      :SDL_IsAudioDevicePhysical,
      :SDL_IsAudioDevicePlayback,
      :SDL_PauseAudioDevice,
      :SDL_ResumeAudioDevice,
      :SDL_AudioDevicePaused,
      :SDL_GetAudioDeviceGain,
      :SDL_SetAudioDeviceGain,
      :SDL_CloseAudioDevice,
      :SDL_BindAudioStreams,
      :SDL_BindAudioStream,
      :SDL_UnbindAudioStreams,
      :SDL_UnbindAudioStream,
      :SDL_GetAudioStreamDevice,
      :SDL_CreateAudioStream,
      :SDL_GetAudioStreamProperties,
      :SDL_GetAudioStreamFormat,
      :SDL_SetAudioStreamFormat,
      :SDL_GetAudioStreamFrequencyRatio,
      :SDL_SetAudioStreamFrequencyRatio,
      :SDL_GetAudioStreamGain,
      :SDL_SetAudioStreamGain,
      :SDL_GetAudioStreamInputChannelMap,
      :SDL_GetAudioStreamOutputChannelMap,
      :SDL_SetAudioStreamInputChannelMap,
      :SDL_SetAudioStreamOutputChannelMap,
      :SDL_PutAudioStreamData,
      :SDL_GetAudioStreamData,
      :SDL_GetAudioStreamAvailable,
      :SDL_GetAudioStreamQueued,
      :SDL_FlushAudioStream,
      :SDL_ClearAudioStream,
      :SDL_PauseAudioStreamDevice,
      :SDL_ResumeAudioStreamDevice,
      :SDL_AudioStreamDevicePaused,
      :SDL_LockAudioStream,
      :SDL_UnlockAudioStream,
      :SDL_SetAudioStreamGetCallback,
      :SDL_SetAudioStreamPutCallback,
      :SDL_DestroyAudioStream,
      :SDL_OpenAudioDeviceStream,
      :SDL_SetAudioPostmixCallback,
      :SDL_LoadWAV_IO,
      :SDL_LoadWAV,
      :SDL_MixAudio,
      :SDL_ConvertAudioSamples,
      :SDL_GetAudioFormatName,
      :SDL_GetSilenceValueForFormat,
    ]
    apis = {
      :SDL_GetNumAudioDrivers => :GetNumAudioDrivers,
      :SDL_GetAudioDriver => :GetAudioDriver,
      :SDL_GetCurrentAudioDriver => :GetCurrentAudioDriver,
      :SDL_GetAudioPlaybackDevices => :GetAudioPlaybackDevices,
      :SDL_GetAudioRecordingDevices => :GetAudioRecordingDevices,
      :SDL_GetAudioDeviceName => :GetAudioDeviceName,
      :SDL_GetAudioDeviceFormat => :GetAudioDeviceFormat,
      :SDL_GetAudioDeviceChannelMap => :GetAudioDeviceChannelMap,
      :SDL_OpenAudioDevice => :OpenAudioDevice,
      :SDL_IsAudioDevicePhysical => :IsAudioDevicePhysical,
      :SDL_IsAudioDevicePlayback => :IsAudioDevicePlayback,
      :SDL_PauseAudioDevice => :PauseAudioDevice,
      :SDL_ResumeAudioDevice => :ResumeAudioDevice,
      :SDL_AudioDevicePaused => :AudioDevicePaused,
      :SDL_GetAudioDeviceGain => :GetAudioDeviceGain,
      :SDL_SetAudioDeviceGain => :SetAudioDeviceGain,
      :SDL_CloseAudioDevice => :CloseAudioDevice,
      :SDL_BindAudioStreams => :BindAudioStreams,
      :SDL_BindAudioStream => :BindAudioStream,
      :SDL_UnbindAudioStreams => :UnbindAudioStreams,
      :SDL_UnbindAudioStream => :UnbindAudioStream,
      :SDL_GetAudioStreamDevice => :GetAudioStreamDevice,
      :SDL_CreateAudioStream => :CreateAudioStream,
      :SDL_GetAudioStreamProperties => :GetAudioStreamProperties,
      :SDL_GetAudioStreamFormat => :GetAudioStreamFormat,
      :SDL_SetAudioStreamFormat => :SetAudioStreamFormat,
      :SDL_GetAudioStreamFrequencyRatio => :GetAudioStreamFrequencyRatio,
      :SDL_SetAudioStreamFrequencyRatio => :SetAudioStreamFrequencyRatio,
      :SDL_GetAudioStreamGain => :GetAudioStreamGain,
      :SDL_SetAudioStreamGain => :SetAudioStreamGain,
      :SDL_GetAudioStreamInputChannelMap => :GetAudioStreamInputChannelMap,
      :SDL_GetAudioStreamOutputChannelMap => :GetAudioStreamOutputChannelMap,
      :SDL_SetAudioStreamInputChannelMap => :SetAudioStreamInputChannelMap,
      :SDL_SetAudioStreamOutputChannelMap => :SetAudioStreamOutputChannelMap,
      :SDL_PutAudioStreamData => :PutAudioStreamData,
      :SDL_GetAudioStreamData => :GetAudioStreamData,
      :SDL_GetAudioStreamAvailable => :GetAudioStreamAvailable,
      :SDL_GetAudioStreamQueued => :GetAudioStreamQueued,
      :SDL_FlushAudioStream => :FlushAudioStream,
      :SDL_ClearAudioStream => :ClearAudioStream,
      :SDL_PauseAudioStreamDevice => :PauseAudioStreamDevice,
      :SDL_ResumeAudioStreamDevice => :ResumeAudioStreamDevice,
      :SDL_AudioStreamDevicePaused => :AudioStreamDevicePaused,
      :SDL_LockAudioStream => :LockAudioStream,
      :SDL_UnlockAudioStream => :UnlockAudioStream,
      :SDL_SetAudioStreamGetCallback => :SetAudioStreamGetCallback,
      :SDL_SetAudioStreamPutCallback => :SetAudioStreamPutCallback,
      :SDL_DestroyAudioStream => :DestroyAudioStream,
      :SDL_OpenAudioDeviceStream => :OpenAudioDeviceStream,
      :SDL_SetAudioPostmixCallback => :SetAudioPostmixCallback,
      :SDL_LoadWAV_IO => :LoadWAV_IO,
      :SDL_LoadWAV => :LoadWAV,
      :SDL_MixAudio => :MixAudio,
      :SDL_ConvertAudioSamples => :ConvertAudioSamples,
      :SDL_GetAudioFormatName => :GetAudioFormatName,
      :SDL_GetSilenceValueForFormat => :GetSilenceValueForFormat,
    }
    args = {
      :SDL_GetNumAudioDrivers => [],
      :SDL_GetAudioDriver => [:int],
      :SDL_GetCurrentAudioDriver => [],
      :SDL_GetAudioPlaybackDevices => [:pointer],
      :SDL_GetAudioRecordingDevices => [:pointer],
      :SDL_GetAudioDeviceName => [:uint],
      :SDL_GetAudioDeviceFormat => [:uint, :pointer, :pointer],
      :SDL_GetAudioDeviceChannelMap => [:uint, :pointer],
      :SDL_OpenAudioDevice => [:uint, :pointer],
      :SDL_IsAudioDevicePhysical => [:uint],
      :SDL_IsAudioDevicePlayback => [:uint],
      :SDL_PauseAudioDevice => [:uint],
      :SDL_ResumeAudioDevice => [:uint],
      :SDL_AudioDevicePaused => [:uint],
      :SDL_GetAudioDeviceGain => [:uint],
      :SDL_SetAudioDeviceGain => [:uint, :float],
      :SDL_CloseAudioDevice => [:uint],
      :SDL_BindAudioStreams => [:uint, :pointer, :int],
      :SDL_BindAudioStream => [:uint, :pointer],
      :SDL_UnbindAudioStreams => [:pointer, :int],
      :SDL_UnbindAudioStream => [:pointer],
      :SDL_GetAudioStreamDevice => [:pointer],
      :SDL_CreateAudioStream => [:pointer, :pointer],
      :SDL_GetAudioStreamProperties => [:pointer],
      :SDL_GetAudioStreamFormat => [:pointer, :pointer, :pointer],
      :SDL_SetAudioStreamFormat => [:pointer, :pointer, :pointer],
      :SDL_GetAudioStreamFrequencyRatio => [:pointer],
      :SDL_SetAudioStreamFrequencyRatio => [:pointer, :float],
      :SDL_GetAudioStreamGain => [:pointer],
      :SDL_SetAudioStreamGain => [:pointer, :float],
      :SDL_GetAudioStreamInputChannelMap => [:pointer, :pointer],
      :SDL_GetAudioStreamOutputChannelMap => [:pointer, :pointer],
      :SDL_SetAudioStreamInputChannelMap => [:pointer, :pointer, :int],
      :SDL_SetAudioStreamOutputChannelMap => [:pointer, :pointer, :int],
      :SDL_PutAudioStreamData => [:pointer, :pointer, :int],
      :SDL_GetAudioStreamData => [:pointer, :pointer, :int],
      :SDL_GetAudioStreamAvailable => [:pointer],
      :SDL_GetAudioStreamQueued => [:pointer],
      :SDL_FlushAudioStream => [:pointer],
      :SDL_ClearAudioStream => [:pointer],
      :SDL_PauseAudioStreamDevice => [:pointer],
      :SDL_ResumeAudioStreamDevice => [:pointer],
      :SDL_AudioStreamDevicePaused => [:pointer],
      :SDL_LockAudioStream => [:pointer],
      :SDL_UnlockAudioStream => [:pointer],
      :SDL_SetAudioStreamGetCallback => [:pointer, :SDL_AudioStreamCallback, :pointer],
      :SDL_SetAudioStreamPutCallback => [:pointer, :SDL_AudioStreamCallback, :pointer],
      :SDL_DestroyAudioStream => [:pointer],
      :SDL_OpenAudioDeviceStream => [:uint, :pointer, :SDL_AudioStreamCallback, :pointer],
      :SDL_SetAudioPostmixCallback => [:uint, :SDL_AudioPostmixCallback, :pointer],
      :SDL_LoadWAV_IO => [:pointer, :bool, :pointer, :pointer, :pointer],
      :SDL_LoadWAV => [:pointer, :pointer, :pointer, :pointer],
      :SDL_MixAudio => [:pointer, :pointer, :int, :uint, :float],
      :SDL_ConvertAudioSamples => [:pointer, :pointer, :int, :pointer, :pointer, :pointer],
      :SDL_GetAudioFormatName => [:int],
      :SDL_GetSilenceValueForFormat => [:int],
    }
    retvals = {
      :SDL_GetNumAudioDrivers => :int,
      :SDL_GetAudioDriver => :pointer,
      :SDL_GetCurrentAudioDriver => :pointer,
      :SDL_GetAudioPlaybackDevices => :pointer,
      :SDL_GetAudioRecordingDevices => :pointer,
      :SDL_GetAudioDeviceName => :pointer,
      :SDL_GetAudioDeviceFormat => :bool,
      :SDL_GetAudioDeviceChannelMap => :pointer,
      :SDL_OpenAudioDevice => :uint,
      :SDL_IsAudioDevicePhysical => :bool,
      :SDL_IsAudioDevicePlayback => :bool,
      :SDL_PauseAudioDevice => :bool,
      :SDL_ResumeAudioDevice => :bool,
      :SDL_AudioDevicePaused => :bool,
      :SDL_GetAudioDeviceGain => :float,
      :SDL_SetAudioDeviceGain => :bool,
      :SDL_CloseAudioDevice => :void,
      :SDL_BindAudioStreams => :bool,
      :SDL_BindAudioStream => :bool,
      :SDL_UnbindAudioStreams => :void,
      :SDL_UnbindAudioStream => :void,
      :SDL_GetAudioStreamDevice => :uint,
      :SDL_CreateAudioStream => :pointer,
      :SDL_GetAudioStreamProperties => :uint,
      :SDL_GetAudioStreamFormat => :bool,
      :SDL_SetAudioStreamFormat => :bool,
      :SDL_GetAudioStreamFrequencyRatio => :float,
      :SDL_SetAudioStreamFrequencyRatio => :bool,
      :SDL_GetAudioStreamGain => :float,
      :SDL_SetAudioStreamGain => :bool,
      :SDL_GetAudioStreamInputChannelMap => :pointer,
      :SDL_GetAudioStreamOutputChannelMap => :pointer,
      :SDL_SetAudioStreamInputChannelMap => :bool,
      :SDL_SetAudioStreamOutputChannelMap => :bool,
      :SDL_PutAudioStreamData => :bool,
      :SDL_GetAudioStreamData => :int,
      :SDL_GetAudioStreamAvailable => :int,
      :SDL_GetAudioStreamQueued => :int,
      :SDL_FlushAudioStream => :bool,
      :SDL_ClearAudioStream => :bool,
      :SDL_PauseAudioStreamDevice => :bool,
      :SDL_ResumeAudioStreamDevice => :bool,
      :SDL_AudioStreamDevicePaused => :bool,
      :SDL_LockAudioStream => :bool,
      :SDL_UnlockAudioStream => :bool,
      :SDL_SetAudioStreamGetCallback => :bool,
      :SDL_SetAudioStreamPutCallback => :bool,
      :SDL_DestroyAudioStream => :void,
      :SDL_OpenAudioDeviceStream => :pointer,
      :SDL_SetAudioPostmixCallback => :bool,
      :SDL_LoadWAV_IO => :bool,
      :SDL_LoadWAV => :bool,
      :SDL_MixAudio => :bool,
      :SDL_ConvertAudioSamples => :bool,
      :SDL_GetAudioFormatName => :pointer,
      :SDL_GetSilenceValueForFormat => :int,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

# TODO : def SDL_LoadWAV

