# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  PEN_MOUSEID = -2
  PEN_TOUCHID = -2
  PEN_INPUT_DOWN = 1 << 0
  PEN_INPUT_BUTTON_1 = 1 << 1
  PEN_INPUT_BUTTON_2 = 1 << 2
  PEN_INPUT_BUTTON_3 = 1 << 3
  PEN_INPUT_BUTTON_4 = 1 << 4
  PEN_INPUT_BUTTON_5 = 1 << 5
  PEN_INPUT_ERASER_TIP = 1 << 30

  # Enum

  PEN_AXIS_PRESSURE = 0
  PEN_AXIS_XTILT = 1
  PEN_AXIS_YTILT = 2
  PEN_AXIS_DISTANCE = 3
  PEN_AXIS_ROTATION = 4
  PEN_AXIS_SLIDER = 5
  PEN_AXIS_TANGENTIAL_PRESSURE = 6
  PEN_AXIS_COUNT = 7

  # Typedef

  typedef :uint, :SDL_PenID
  typedef :uint, :SDL_PenInputFlags
  typedef :int, :SDL_PenAxis

  # Struct


  # Function

  def self.setup_pen_symbols(output_error = false)
    entries = [
    ]
    entries.each do |entry|
      attach_function entry[0], entry[1], entry[2], entry[3]
    rescue FFI::NotFoundError => e
      warn "[Warning] Failed to import #{entry[0]} (#{e})." if output_error
    end
  end

end

