# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  TRAYENTRY_BUTTON = 0x00000001
  TRAYENTRY_CHECKBOX = 0x00000002
  TRAYENTRY_SUBMENU = 0x00000004
  TRAYENTRY_DISABLED = 0x80000000
  TRAYENTRY_CHECKED = 0x40000000

  # Enum


  # Typedef

  typedef :uint, :SDL_TrayEntryFlags
  callback :SDL_TrayCallback, [:pointer, :pointer], :void

  # Struct


  # Function

  def self.setup_tray_symbols(output_error = false)
    symbols = [
      :SDL_CreateTray,
      :SDL_SetTrayIcon,
      :SDL_SetTrayTooltip,
      :SDL_CreateTrayMenu,
      :SDL_CreateTraySubmenu,
      :SDL_GetTrayMenu,
      :SDL_GetTraySubmenu,
      :SDL_GetTrayEntries,
      :SDL_RemoveTrayEntry,
      :SDL_InsertTrayEntryAt,
      :SDL_SetTrayEntryLabel,
      :SDL_GetTrayEntryLabel,
      :SDL_SetTrayEntryChecked,
      :SDL_GetTrayEntryChecked,
      :SDL_SetTrayEntryEnabled,
      :SDL_GetTrayEntryEnabled,
      :SDL_SetTrayEntryCallback,
      :SDL_ClickTrayEntry,
      :SDL_DestroyTray,
      :SDL_GetTrayEntryParent,
      :SDL_GetTrayMenuParentEntry,
      :SDL_GetTrayMenuParentTray,
      :SDL_UpdateTrays,
    ]
    apis = {
      :SDL_CreateTray => :CreateTray,
      :SDL_SetTrayIcon => :SetTrayIcon,
      :SDL_SetTrayTooltip => :SetTrayTooltip,
      :SDL_CreateTrayMenu => :CreateTrayMenu,
      :SDL_CreateTraySubmenu => :CreateTraySubmenu,
      :SDL_GetTrayMenu => :GetTrayMenu,
      :SDL_GetTraySubmenu => :GetTraySubmenu,
      :SDL_GetTrayEntries => :GetTrayEntries,
      :SDL_RemoveTrayEntry => :RemoveTrayEntry,
      :SDL_InsertTrayEntryAt => :InsertTrayEntryAt,
      :SDL_SetTrayEntryLabel => :SetTrayEntryLabel,
      :SDL_GetTrayEntryLabel => :GetTrayEntryLabel,
      :SDL_SetTrayEntryChecked => :SetTrayEntryChecked,
      :SDL_GetTrayEntryChecked => :GetTrayEntryChecked,
      :SDL_SetTrayEntryEnabled => :SetTrayEntryEnabled,
      :SDL_GetTrayEntryEnabled => :GetTrayEntryEnabled,
      :SDL_SetTrayEntryCallback => :SetTrayEntryCallback,
      :SDL_ClickTrayEntry => :ClickTrayEntry,
      :SDL_DestroyTray => :DestroyTray,
      :SDL_GetTrayEntryParent => :GetTrayEntryParent,
      :SDL_GetTrayMenuParentEntry => :GetTrayMenuParentEntry,
      :SDL_GetTrayMenuParentTray => :GetTrayMenuParentTray,
      :SDL_UpdateTrays => :UpdateTrays,
    }
    args = {
      :SDL_CreateTray => [:pointer, :pointer],
      :SDL_SetTrayIcon => [:pointer, :pointer],
      :SDL_SetTrayTooltip => [:pointer, :pointer],
      :SDL_CreateTrayMenu => [:pointer],
      :SDL_CreateTraySubmenu => [:pointer],
      :SDL_GetTrayMenu => [:pointer],
      :SDL_GetTraySubmenu => [:pointer],
      :SDL_GetTrayEntries => [:pointer, :pointer],
      :SDL_RemoveTrayEntry => [:pointer],
      :SDL_InsertTrayEntryAt => [:pointer, :int, :pointer, :uint],
      :SDL_SetTrayEntryLabel => [:pointer, :pointer],
      :SDL_GetTrayEntryLabel => [:pointer],
      :SDL_SetTrayEntryChecked => [:pointer, :bool],
      :SDL_GetTrayEntryChecked => [:pointer],
      :SDL_SetTrayEntryEnabled => [:pointer, :bool],
      :SDL_GetTrayEntryEnabled => [:pointer],
      :SDL_SetTrayEntryCallback => [:pointer, :SDL_TrayCallback, :pointer],
      :SDL_ClickTrayEntry => [:pointer],
      :SDL_DestroyTray => [:pointer],
      :SDL_GetTrayEntryParent => [:pointer],
      :SDL_GetTrayMenuParentEntry => [:pointer],
      :SDL_GetTrayMenuParentTray => [:pointer],
      :SDL_UpdateTrays => [],
    }
    retvals = {
      :SDL_CreateTray => :pointer,
      :SDL_SetTrayIcon => :void,
      :SDL_SetTrayTooltip => :void,
      :SDL_CreateTrayMenu => :pointer,
      :SDL_CreateTraySubmenu => :pointer,
      :SDL_GetTrayMenu => :pointer,
      :SDL_GetTraySubmenu => :pointer,
      :SDL_GetTrayEntries => :pointer,
      :SDL_RemoveTrayEntry => :void,
      :SDL_InsertTrayEntryAt => :pointer,
      :SDL_SetTrayEntryLabel => :void,
      :SDL_GetTrayEntryLabel => :pointer,
      :SDL_SetTrayEntryChecked => :void,
      :SDL_GetTrayEntryChecked => :bool,
      :SDL_SetTrayEntryEnabled => :void,
      :SDL_GetTrayEntryEnabled => :bool,
      :SDL_SetTrayEntryCallback => :void,
      :SDL_ClickTrayEntry => :void,
      :SDL_DestroyTray => :void,
      :SDL_GetTrayEntryParent => :pointer,
      :SDL_GetTrayMenuParentEntry => :pointer,
      :SDL_GetTrayMenuParentTray => :pointer,
      :SDL_UpdateTrays => :void,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

