# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  SHADERCROSS_MAJOR_VERSION = 3
  SHADERCROSS_MINOR_VERSION = 0
  SHADERCROSS_MICRO_VERSION = 0
  SHADERCROSS_PROP_SHADER_DEBUG_ENABLE_BOOLEAN = "SDL_shadercross.spirv.debug.enable"
  SHADERCROSS_PROP_SHADER_DEBUG_NAME_STRING = "SDL_shadercross.spirv.debug.name"
  SHADERCROSS_PROP_SHADER_CULL_UNUSED_BINDINGS_BOOLEAN = "SDL_shadercross.spirv.cull_unused_bindings"
  SHADERCROSS_PROP_SPIRV_PSSL_COMPATIBILITY_BOOLEAN = "SDL_shadercross.spirv.pssl.compatibility"
  SHADERCROSS_PROP_SPIRV_MSL_VERSION_STRING = "SDL_shadercross.spirv.msl.version"
  SHADERCROSS_PROP_HLSL_SKIP_SPIRV_ROUNDTRIP_BOOLEAN = "SDL_shadercross.hlsl.skip_spirv_roundtrip"

  # Enum

  SHADERCROSS_IOVAR_TYPE_UNKNOWN = 0
  SHADERCROSS_IOVAR_TYPE_INT8 = 1
  SHADERCROSS_IOVAR_TYPE_UINT8 = 2
  SHADERCROSS_IOVAR_TYPE_INT16 = 3
  SHADERCROSS_IOVAR_TYPE_UINT16 = 4
  SHADERCROSS_IOVAR_TYPE_INT32 = 5
  SHADERCROSS_IOVAR_TYPE_UINT32 = 6
  SHADERCROSS_IOVAR_TYPE_INT64 = 7
  SHADERCROSS_IOVAR_TYPE_UINT64 = 8
  SHADERCROSS_IOVAR_TYPE_FLOAT16 = 9
  SHADERCROSS_IOVAR_TYPE_FLOAT32 = 10
  SHADERCROSS_IOVAR_TYPE_FLOAT64 = 11
  SHADERCROSS_SHADERSTAGE_VERTEX = 0
  SHADERCROSS_SHADERSTAGE_FRAGMENT = 1
  SHADERCROSS_SHADERSTAGE_COMPUTE = 2

  # Typedef

  typedef :int, :SDL_ShaderCross_IOVarType
  typedef :int, :SDL_ShaderCross_ShaderStage

  # Struct

  class ShaderCross_IOVarMetadata < FFI::Struct
    layout(
      :name, :pointer,
      :location, :uint,
      :vector_type, :int,
      :vector_size, :uint,
    )
  end

  class ShaderCross_GraphicsShaderResourceInfo < FFI::Struct
    layout(
      :num_samplers, :uint,
      :num_storage_textures, :uint,
      :num_storage_buffers, :uint,
      :num_uniform_buffers, :uint,
    )
  end

  class ShaderCross_GraphicsShaderMetadata < FFI::Struct
    layout(
      :resource_info, ShaderCross_GraphicsShaderResourceInfo,
      :num_inputs, :uint,
      :inputs, :pointer,
      :num_outputs, :uint,
      :outputs, :pointer,
    )
  end

  class ShaderCross_ComputePipelineMetadata < FFI::Struct
    layout(
      :num_samplers, :uint,
      :num_readonly_storage_textures, :uint,
      :num_readonly_storage_buffers, :uint,
      :num_readwrite_storage_textures, :uint,
      :num_readwrite_storage_buffers, :uint,
      :num_uniform_buffers, :uint,
      :threadcount_x, :uint,
      :threadcount_y, :uint,
      :threadcount_z, :uint,
    )
  end

  class ShaderCross_SPIRV_Info < FFI::Struct
    layout(
      :bytecode, :pointer,
      :bytecode_size, :ulong_long,
      :entrypoint, :pointer,
      :shader_stage, :int,
      :props, :uint,
    )
  end

  class ShaderCross_HLSL_Define < FFI::Struct
    layout(
      :name, :pointer,
      :value, :pointer,
    )
  end

  class ShaderCross_HLSL_Info < FFI::Struct
    layout(
      :source, :pointer,
      :entrypoint, :pointer,
      :include_dir, :pointer,
      :defines, :pointer,
      :shader_stage, :int,
      :props, :uint,
    )
  end


  # Function

  def self.setup_shadercross_symbols(output_error = false)
    entries = [
      [:ShaderCross_Init, :SDL_ShaderCross_Init, [], :bool],
      [:ShaderCross_Quit, :SDL_ShaderCross_Quit, [], :void],
      [:ShaderCross_GetSPIRVShaderFormats, :SDL_ShaderCross_GetSPIRVShaderFormats, [], :uint],
      [:ShaderCross_TranspileMSLFromSPIRV, :SDL_ShaderCross_TranspileMSLFromSPIRV, [:pointer], :pointer],
      [:ShaderCross_TranspileHLSLFromSPIRV, :SDL_ShaderCross_TranspileHLSLFromSPIRV, [:pointer], :pointer],
      [:ShaderCross_CompileDXBCFromSPIRV, :SDL_ShaderCross_CompileDXBCFromSPIRV, [:pointer, :pointer], :pointer],
      [:ShaderCross_CompileDXILFromSPIRV, :SDL_ShaderCross_CompileDXILFromSPIRV, [:pointer, :pointer], :pointer],
      [:ShaderCross_CompileGraphicsShaderFromSPIRV, :SDL_ShaderCross_CompileGraphicsShaderFromSPIRV, [:pointer, :pointer, :pointer, :uint], :pointer],
      [:ShaderCross_CompileComputePipelineFromSPIRV, :SDL_ShaderCross_CompileComputePipelineFromSPIRV, [:pointer, :pointer, :pointer, :uint], :pointer],
      [:ShaderCross_ReflectGraphicsSPIRV, :SDL_ShaderCross_ReflectGraphicsSPIRV, [:pointer, :ulong_long, :uint], :pointer],
      [:ShaderCross_ReflectComputeSPIRV, :SDL_ShaderCross_ReflectComputeSPIRV, [:pointer, :ulong_long, :uint], :pointer],
      [:ShaderCross_GetHLSLShaderFormats, :SDL_ShaderCross_GetHLSLShaderFormats, [], :uint],
      [:ShaderCross_CompileDXBCFromHLSL, :SDL_ShaderCross_CompileDXBCFromHLSL, [:pointer, :pointer], :pointer],
      [:ShaderCross_CompileDXILFromHLSL, :SDL_ShaderCross_CompileDXILFromHLSL, [:pointer, :pointer], :pointer],
      [:ShaderCross_CompileSPIRVFromHLSL, :SDL_ShaderCross_CompileSPIRVFromHLSL, [:pointer, :pointer], :pointer],
    ]
    entries.each do |entry|
      attach_function entry[0], entry[1], entry[2], entry[3]
    rescue FFI::NotFoundError => e
      warn "[Warning] Failed to import #{entry[0]} (#{e})." if output_error
    end
  end

end

