# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  MIXER_MAJOR_VERSION = 3
  MIXER_MINOR_VERSION = 1
  MIXER_MICRO_VERSION = 0
  MIX_PROP_MIXER_DEVICE_NUMBER = "SDL_mixer.mixer.device"
  MIX_PROP_AUDIO_LOAD_IOSTREAM_POINTER = "SDL_mixer.audio.load.iostream"
  MIX_PROP_AUDIO_LOAD_CLOSEIO_BOOLEAN = "SDL_mixer.audio.load.closeio"
  MIX_PROP_AUDIO_LOAD_PREDECODE_BOOLEAN = "SDL_mixer.audio.load.predecode"
  MIX_PROP_AUDIO_LOAD_PREFERRED_MIXER_POINTER = "SDL_mixer.audio.load.preferred_mixer"
  MIX_PROP_AUDIO_LOAD_SKIP_METADATA_TAGS_BOOLEAN = "SDL_mixer.audio.load.skip_metadata_tags"
  MIX_PROP_AUDIO_DECODER_STRING = "SDL_mixer.audio.decoder"
  MIX_PROP_METADATA_TITLE_STRING = "SDL_mixer.metadata.title"
  MIX_PROP_METADATA_ARTIST_STRING = "SDL_mixer.metadata.artist"
  MIX_PROP_METADATA_ALBUM_STRING = "SDL_mixer.metadata.album"
  MIX_PROP_METADATA_COPYRIGHT_STRING = "SDL_mixer.metadata.copyright"
  MIX_PROP_METADATA_TRACK_NUMBER = "SDL_mixer.metadata.track"
  MIX_PROP_METADATA_TOTAL_TRACKS_NUMBER = "SDL_mixer.metadata.total_tracks"
  MIX_PROP_METADATA_YEAR_NUMBER = "SDL_mixer.metadata.year"
  MIX_PROP_METADATA_DURATION_FRAMES_NUMBER = "SDL_mixer.metadata.duration_frames"
  MIX_PROP_METADATA_DURATION_INFINITE_BOOLEAN = "SDL_mixer.metadata.duration_infinite"
  MIX_DURATION_UNKNOWN = -1
  MIX_DURATION_INFINITE = -2
  MIX_PROP_PLAY_LOOPS_NUMBER = "SDL_mixer.play.loops"
  MIX_PROP_PLAY_MAX_FRAME_NUMBER = "SDL_mixer.play.max_frame"
  MIX_PROP_PLAY_MAX_MILLISECONDS_NUMBER = "SDL_mixer.play.max_milliseconds"
  MIX_PROP_PLAY_START_FRAME_NUMBER = "SDL_mixer.play.start_frame"
  MIX_PROP_PLAY_START_MILLISECOND_NUMBER = "SDL_mixer.play.start_millisecond"
  MIX_PROP_PLAY_LOOP_START_FRAME_NUMBER = "SDL_mixer.play.loop_start_frame"
  MIX_PROP_PLAY_LOOP_START_MILLISECOND_NUMBER = "SDL_mixer.play.loop_start_millisecond"
  MIX_PROP_PLAY_FADE_IN_FRAMES_NUMBER = "SDL_mixer.play.fade_in_frames"
  MIX_PROP_PLAY_FADE_IN_MILLISECONDS_NUMBER = "SDL_mixer.play.fade_in_milliseconds"
  MIX_PROP_PLAY_APPEND_SILENCE_FRAMES_NUMBER = "SDL_mixer.play.append_silence_frames"
  MIX_PROP_PLAY_APPEND_SILENCE_MILLISECONDS_NUMBER = "SDL_mixer.play.append_silence_milliseconds"

  # Enum


  # Typedef

  callback :MIX_TrackStoppedCallback, [:pointer, :pointer], :void
  callback :MIX_TrackMixCallback, [:pointer, :pointer, :pointer, :pointer, :int], :void
  callback :MIX_GroupMixCallback, [:pointer, :pointer, :pointer, :pointer, :int], :void
  callback :MIX_PostMixCallback, [:pointer, :pointer, :pointer, :pointer, :int], :void

  # Struct

  class MIX_StereoGains < FFI::Struct
    layout(
      :left, :float,
      :right, :float,
    )
  end

  class MIX_Point3D < FFI::Struct
    layout(
      :x, :float,
      :y, :float,
      :z, :float,
    )
  end


  # Function

  def self.setup_mixer_symbols(output_error = false)
    entries = [
      [:MIX_Version, :MIX_Version, [], :int],
      [:MIX_Init, :MIX_Init, [], :bool],
      [:MIX_Quit, :MIX_Quit, [], :void],
      [:MIX_GetNumAudioDecoders, :MIX_GetNumAudioDecoders, [], :int],
      [:MIX_GetAudioDecoder, :MIX_GetAudioDecoder, [:int], :pointer],
      [:MIX_CreateMixerDevice, :MIX_CreateMixerDevice, [:uint, :pointer], :pointer],
      [:MIX_CreateMixer, :MIX_CreateMixer, [:pointer], :pointer],
      [:MIX_DestroyMixer, :MIX_DestroyMixer, [:pointer], :void],
      [:MIX_GetMixerProperties, :MIX_GetMixerProperties, [:pointer], :uint],
      [:MIX_GetMixerFormat, :MIX_GetMixerFormat, [:pointer, :pointer], :bool],
      [:MIX_LoadAudio_IO, :MIX_LoadAudio_IO, [:pointer, :pointer, :bool, :bool], :pointer],
      [:MIX_LoadAudio, :MIX_LoadAudio, [:pointer, :pointer, :bool], :pointer],
      [:MIX_LoadAudioWithProperties, :MIX_LoadAudioWithProperties, [:uint], :pointer],
      [:MIX_LoadRawAudio_IO, :MIX_LoadRawAudio_IO, [:pointer, :pointer, :pointer, :bool], :pointer],
      [:MIX_LoadRawAudio, :MIX_LoadRawAudio, [:pointer, :pointer, :ulong_long, :pointer], :pointer],
      [:MIX_LoadRawAudioNoCopy, :MIX_LoadRawAudioNoCopy, [:pointer, :pointer, :ulong_long, :pointer, :bool], :pointer],
      [:MIX_CreateSineWaveAudio, :MIX_CreateSineWaveAudio, [:pointer, :int, :float], :pointer],
      [:MIX_GetAudioProperties, :MIX_GetAudioProperties, [:pointer], :uint],
      [:MIX_GetAudioDuration, :MIX_GetAudioDuration, [:pointer], :long_long],
      [:MIX_GetAudioFormat, :MIX_GetAudioFormat, [:pointer, :pointer], :bool],
      [:MIX_DestroyAudio, :MIX_DestroyAudio, [:pointer], :void],
      [:MIX_CreateTrack, :MIX_CreateTrack, [:pointer], :pointer],
      [:MIX_DestroyTrack, :MIX_DestroyTrack, [:pointer], :void],
      [:MIX_GetTrackProperties, :MIX_GetTrackProperties, [:pointer], :uint],
      [:MIX_GetTrackMixer, :MIX_GetTrackMixer, [:pointer], :pointer],
      [:MIX_SetTrackAudio, :MIX_SetTrackAudio, [:pointer, :pointer], :bool],
      [:MIX_SetTrackAudioStream, :MIX_SetTrackAudioStream, [:pointer, :pointer], :bool],
      [:MIX_SetTrackIOStream, :MIX_SetTrackIOStream, [:pointer, :pointer, :bool], :bool],
      [:MIX_SetTrackRawIOStream, :MIX_SetTrackRawIOStream, [:pointer, :pointer, :pointer, :bool], :bool],
      [:MIX_TagTrack, :MIX_TagTrack, [:pointer, :pointer], :bool],
      [:MIX_UntagTrack, :MIX_UntagTrack, [:pointer, :pointer], :void],
      [:MIX_GetTrackTags, :MIX_GetTrackTags, [:pointer, :pointer], :pointer],
      [:MIX_GetTaggedTracks, :MIX_GetTaggedTracks, [:pointer, :pointer, :pointer], :pointer],
      [:MIX_SetTrackPlaybackPosition, :MIX_SetTrackPlaybackPosition, [:pointer, :long_long], :bool],
      [:MIX_GetTrackPlaybackPosition, :MIX_GetTrackPlaybackPosition, [:pointer], :long_long],
      [:MIX_GetTrackFadeFrames, :MIX_GetTrackFadeFrames, [:pointer], :long_long],
      [:MIX_TrackLooping, :MIX_TrackLooping, [:pointer], :bool],
      [:MIX_SetTrackLoops, :MIX_SetTrackLoops, [:pointer, :int], :bool],
      [:MIX_GetTrackAudio, :MIX_GetTrackAudio, [:pointer], :pointer],
      [:MIX_GetTrackAudioStream, :MIX_GetTrackAudioStream, [:pointer], :pointer],
      [:MIX_GetTrackRemaining, :MIX_GetTrackRemaining, [:pointer], :long_long],
      [:MIX_TrackMSToFrames, :MIX_TrackMSToFrames, [:pointer, :long_long], :long_long],
      [:MIX_TrackFramesToMS, :MIX_TrackFramesToMS, [:pointer, :long_long], :long_long],
      [:MIX_AudioMSToFrames, :MIX_AudioMSToFrames, [:pointer, :long_long], :long_long],
      [:MIX_AudioFramesToMS, :MIX_AudioFramesToMS, [:pointer, :long_long], :long_long],
      [:MIX_MSToFrames, :MIX_MSToFrames, [:int, :long_long], :long_long],
      [:MIX_FramesToMS, :MIX_FramesToMS, [:int, :long_long], :long_long],
      [:MIX_PlayTrack, :MIX_PlayTrack, [:pointer, :uint], :bool],
      [:MIX_PlayTag, :MIX_PlayTag, [:pointer, :pointer, :uint], :bool],
      [:MIX_PlayAudio, :MIX_PlayAudio, [:pointer, :pointer], :bool],
      [:MIX_StopTrack, :MIX_StopTrack, [:pointer, :long_long], :bool],
      [:MIX_StopAllTracks, :MIX_StopAllTracks, [:pointer, :long_long], :bool],
      [:MIX_StopTag, :MIX_StopTag, [:pointer, :pointer, :long_long], :bool],
      [:MIX_PauseTrack, :MIX_PauseTrack, [:pointer], :bool],
      [:MIX_PauseAllTracks, :MIX_PauseAllTracks, [:pointer], :bool],
      [:MIX_PauseTag, :MIX_PauseTag, [:pointer, :pointer], :bool],
      [:MIX_ResumeTrack, :MIX_ResumeTrack, [:pointer], :bool],
      [:MIX_ResumeAllTracks, :MIX_ResumeAllTracks, [:pointer], :bool],
      [:MIX_ResumeTag, :MIX_ResumeTag, [:pointer, :pointer], :bool],
      [:MIX_TrackPlaying, :MIX_TrackPlaying, [:pointer], :bool],
      [:MIX_TrackPaused, :MIX_TrackPaused, [:pointer], :bool],
      [:MIX_SetMasterGain, :MIX_SetMasterGain, [:pointer, :float], :bool],
      [:MIX_GetMasterGain, :MIX_GetMasterGain, [:pointer], :float],
      [:MIX_SetTrackGain, :MIX_SetTrackGain, [:pointer, :float], :bool],
      [:MIX_GetTrackGain, :MIX_GetTrackGain, [:pointer], :float],
      [:MIX_SetTagGain, :MIX_SetTagGain, [:pointer, :pointer, :float], :bool],
      [:MIX_SetTrackFrequencyRatio, :MIX_SetTrackFrequencyRatio, [:pointer, :float], :bool],
      [:MIX_GetTrackFrequencyRatio, :MIX_GetTrackFrequencyRatio, [:pointer], :float],
      [:MIX_SetTrackOutputChannelMap, :MIX_SetTrackOutputChannelMap, [:pointer, :pointer, :int], :bool],
      [:MIX_SetTrackStereo, :MIX_SetTrackStereo, [:pointer, :pointer], :bool],
      [:MIX_SetTrack3DPosition, :MIX_SetTrack3DPosition, [:pointer, :pointer], :bool],
      [:MIX_GetTrack3DPosition, :MIX_GetTrack3DPosition, [:pointer, :pointer], :bool],
      [:MIX_CreateGroup, :MIX_CreateGroup, [:pointer], :pointer],
      [:MIX_DestroyGroup, :MIX_DestroyGroup, [:pointer], :void],
      [:MIX_GetGroupProperties, :MIX_GetGroupProperties, [:pointer], :uint],
      [:MIX_GetGroupMixer, :MIX_GetGroupMixer, [:pointer], :pointer],
      [:MIX_SetTrackGroup, :MIX_SetTrackGroup, [:pointer, :pointer], :bool],
      [:MIX_SetTrackStoppedCallback, :MIX_SetTrackStoppedCallback, [:pointer, :MIX_TrackStoppedCallback, :pointer], :bool],
      [:MIX_SetTrackRawCallback, :MIX_SetTrackRawCallback, [:pointer, :MIX_TrackMixCallback, :pointer], :bool],
      [:MIX_SetTrackCookedCallback, :MIX_SetTrackCookedCallback, [:pointer, :MIX_TrackMixCallback, :pointer], :bool],
      [:MIX_SetGroupPostMixCallback, :MIX_SetGroupPostMixCallback, [:pointer, :MIX_GroupMixCallback, :pointer], :bool],
      [:MIX_SetPostMixCallback, :MIX_SetPostMixCallback, [:pointer, :MIX_PostMixCallback, :pointer], :bool],
      [:MIX_Generate, :MIX_Generate, [:pointer, :pointer, :int], :bool],
      [:MIX_CreateAudioDecoder, :MIX_CreateAudioDecoder, [:pointer, :uint], :pointer],
      [:MIX_CreateAudioDecoder_IO, :MIX_CreateAudioDecoder_IO, [:pointer, :bool, :uint], :pointer],
      [:MIX_DestroyAudioDecoder, :MIX_DestroyAudioDecoder, [:pointer], :void],
      [:MIX_GetAudioDecoderProperties, :MIX_GetAudioDecoderProperties, [:pointer], :uint],
      [:MIX_GetAudioDecoderFormat, :MIX_GetAudioDecoderFormat, [:pointer, :pointer], :bool],
      [:MIX_DecodeAudio, :MIX_DecodeAudio, [:pointer, :pointer, :int, :pointer], :int],
    ]
    entries.each do |entry|
      attach_function entry[0], entry[1], entry[2], entry[3]
    rescue FFI::NotFoundError => e
      warn "[Warning] Failed to import #{entry[0]} (#{e})." if output_error
    end
  end

end

