# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro


  # Enum


  # Typedef


  # Struct


  # Function

  def self.setup_bits_symbols(output_error = false)
    symbols = [
      :SDL_MostSignificantBitIndex32,
      :SDL_HasExactlyOneBitSet32,
    ]
    apis = {
      :SDL_MostSignificantBitIndex32 => :MostSignificantBitIndex32,
      :SDL_HasExactlyOneBitSet32 => :HasExactlyOneBitSet32,
    }
    args = {
      :SDL_MostSignificantBitIndex32 => [:uint],
      :SDL_HasExactlyOneBitSet32 => [:uint],
    }
    retvals = {
      :SDL_MostSignificantBitIndex32 => :int,
      :SDL_HasExactlyOneBitSet32 => :bool,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

