# Ruby-SDL3 : SDL3 wrapper for Ruby
#
# * https://github.com/vaiorabbit/sdl3-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module SDL
  extend FFI::Library
  # Define/Macro

  MESSAGEBOX_ERROR = 0x00000010
  MESSAGEBOX_WARNING = 0x00000020
  MESSAGEBOX_INFORMATION = 0x00000040
  MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT = 0x00000080
  MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT = 0x00000100
  MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT = 0x00000001
  MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT = 0x00000002

  # Enum

  MESSAGEBOX_COLOR_BACKGROUND = 0
  MESSAGEBOX_COLOR_TEXT = 1
  MESSAGEBOX_COLOR_BUTTON_BORDER = 2
  MESSAGEBOX_COLOR_BUTTON_BACKGROUND = 3
  MESSAGEBOX_COLOR_BUTTON_SELECTED = 4
  MESSAGEBOX_COLOR_COUNT = 5

  # Typedef

  typedef :uint, :SDL_MessageBoxFlags
  typedef :uint, :SDL_MessageBoxButtonFlags
  typedef :int, :SDL_MessageBoxColorType

  # Struct

  class MessageBoxButtonData < FFI::Struct
    layout(
      :flags, :uint,
      :buttonID, :int,
      :text, :pointer,
    )
  end

  class MessageBoxColor < FFI::Struct
    layout(
      :r, :uchar,
      :g, :uchar,
      :b, :uchar,
    )
  end

  class MessageBoxColorScheme < FFI::Struct
    layout(
      :colors, [MessageBoxColor, 5],
    )
  end

  class MessageBoxData < FFI::Struct
    layout(
      :flags, :uint,
      :window, :pointer,
      :title, :pointer,
      :message, :pointer,
      :numbuttons, :int,
      :buttons, :pointer,
      :colorScheme, :pointer,
    )
  end


  # Function

  def self.setup_messagebox_symbols(output_error = false)
    entries = [
      [:ShowMessageBox, :SDL_ShowMessageBox, [:pointer, :pointer], :bool],
      [:ShowSimpleMessageBox, :SDL_ShowSimpleMessageBox, [:uint, :pointer, :pointer, :pointer], :bool],
    ]
    entries.each do |entry|
      attach_function entry[0], entry[1], entry[2], entry[3]
    rescue FFI::NotFoundError => e
      warn "[Warning] Failed to import #{entry[0]} (#{e})." if output_error
    end
  end

end

